// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module awn_forward_awn_forward_Pipeline_VITIS_LOOP_277_11 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        fc0_acc_address0,
        fc0_acc_ce0,
        fc0_acc_q0,
        fc0_q_address0,
        fc0_q_ce0,
        fc0_q_we0,
        fc0_q_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [8:0] fc0_acc_address0;
output   fc0_acc_ce0;
input  [21:0] fc0_acc_q0;
output  [8:0] fc0_q_address0;
output   fc0_q_ce0;
output   fc0_q_we0;
output  [7:0] fc0_q_d0;

reg ap_idle;
reg fc0_acc_ce0;
reg fc0_q_ce0;
reg fc0_q_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln277_fu_109_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [63:0] zext_ln277_fu_121_p1;
reg   [63:0] zext_ln277_reg_256;
reg   [63:0] zext_ln277_reg_256_pp0_iter1_reg;
reg   [63:0] zext_ln277_reg_256_pp0_iter2_reg;
reg   [63:0] zext_ln277_reg_256_pp0_iter3_reg;
reg   [63:0] zext_ln277_reg_256_pp0_iter4_reg;
reg   [63:0] zext_ln277_reg_256_pp0_iter5_reg;
reg  signed [21:0] fc0_acc_load_reg_266;
wire   [52:0] prod_fu_96_p2;
reg   [52:0] prod_reg_271;
wire  signed [7:0] r_fu_196_p3;
reg  signed [7:0] r_reg_276;
reg  signed [7:0] r_reg_276_pp0_iter4_reg;
reg  signed [7:0] r_reg_276_pp0_iter5_reg;
reg   [0:0] tmp_272_reg_281;
reg   [0:0] tmp_272_reg_281_pp0_iter4_reg;
reg   [0:0] tmp_272_reg_281_pp0_iter5_reg;
wire    ap_block_pp0_stage0;
reg   [8:0] i_fu_66;
wire   [8:0] add_ln277_fu_115_p2;
wire    ap_loop_init;
reg   [8:0] ap_sig_allocacmp_i_2;
wire   [31:0] prod_fu_96_p1;
wire   [52:0] sum_fu_135_p2;
wire   [7:0] tmp_fu_150_p4;
wire   [14:0] trunc_ln20_6_fu_140_p4;
wire   [0:0] icmp_ln24_fu_160_p2;
wire   [0:0] icmp_ln25_fu_166_p2;
wire   [0:0] or_ln24_fu_190_p2;
wire   [7:0] select_ln24_fu_182_p3;
wire   [7:0] trunc_ln26_7_fu_172_p4;
wire  signed [16:0] trunc_ln_fu_216_p1;
wire   [16:0] grp_fu_236_p3;
wire   [1:0] trunc_ln_fu_216_p4;
wire  signed [7:0] sext_ln26_fu_225_p1;
wire   [8:0] grp_fu_236_p1;
wire   [14:0] grp_fu_236_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 i_fu_66 = 9'd0;
#0 ap_done_reg = 1'b0;
end

awn_forward_mul_22s_32ns_53_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 22 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 53 ))
mul_22s_32ns_53_1_1_U11746(
    .din0(fc0_acc_load_reg_266),
    .din1(prod_fu_96_p1),
    .dout(prod_fu_96_p2)
);

awn_forward_mac_muladd_8s_9ns_15ns_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 9 ),
    .din2_WIDTH( 15 ),
    .dout_WIDTH( 17 ))
mac_muladd_8s_9ns_15ns_17_4_1_U11747(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(r_fu_196_p3),
    .din1(grp_fu_236_p1),
    .din2(grp_fu_236_p2),
    .ce(1'b1),
    .dout(grp_fu_236_p3)
);

awn_forward_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln277_fu_109_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_66 <= add_ln277_fu_115_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_66 <= 9'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        fc0_acc_load_reg_266 <= fc0_acc_q0;
        zext_ln277_reg_256[8 : 0] <= zext_ln277_fu_121_p1[8 : 0];
        zext_ln277_reg_256_pp0_iter1_reg[8 : 0] <= zext_ln277_reg_256[8 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        prod_reg_271 <= prod_fu_96_p2;
        r_reg_276 <= r_fu_196_p3;
        r_reg_276_pp0_iter4_reg <= r_reg_276;
        r_reg_276_pp0_iter5_reg <= r_reg_276_pp0_iter4_reg;
        tmp_272_reg_281 <= r_fu_196_p3[32'd7];
        tmp_272_reg_281_pp0_iter4_reg <= tmp_272_reg_281;
        tmp_272_reg_281_pp0_iter5_reg <= tmp_272_reg_281_pp0_iter4_reg;
        zext_ln277_reg_256_pp0_iter2_reg[8 : 0] <= zext_ln277_reg_256_pp0_iter1_reg[8 : 0];
        zext_ln277_reg_256_pp0_iter3_reg[8 : 0] <= zext_ln277_reg_256_pp0_iter2_reg[8 : 0];
        zext_ln277_reg_256_pp0_iter4_reg[8 : 0] <= zext_ln277_reg_256_pp0_iter3_reg[8 : 0];
        zext_ln277_reg_256_pp0_iter5_reg[8 : 0] <= zext_ln277_reg_256_pp0_iter4_reg[8 : 0];
    end
end

always @ (*) begin
    if (((icmp_ln277_fu_109_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_2 = 9'd0;
    end else begin
        ap_sig_allocacmp_i_2 = i_fu_66;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        fc0_acc_ce0 = 1'b1;
    end else begin
        fc0_acc_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        fc0_q_ce0 = 1'b1;
    end else begin
        fc0_q_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        fc0_q_we0 = 1'b1;
    end else begin
        fc0_q_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln277_fu_115_p2 = (ap_sig_allocacmp_i_2 + 9'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign fc0_acc_address0 = zext_ln277_fu_121_p1;

assign fc0_q_address0 = zext_ln277_reg_256_pp0_iter5_reg;

assign fc0_q_d0 = ((tmp_272_reg_281_pp0_iter5_reg[0:0] == 1'b1) ? sext_ln26_fu_225_p1 : r_reg_276_pp0_iter5_reg);

assign grp_fu_236_p1 = 17'd328;

assign grp_fu_236_p2 = 17'd16384;

assign icmp_ln24_fu_160_p2 = (($signed(tmp_fu_150_p4) > $signed(8'd0)) ? 1'b1 : 1'b0);

assign icmp_ln25_fu_166_p2 = (($signed(trunc_ln20_6_fu_140_p4) < $signed(15'd32640)) ? 1'b1 : 1'b0);

assign icmp_ln277_fu_109_p2 = ((ap_sig_allocacmp_i_2 == 9'd320) ? 1'b1 : 1'b0);

assign or_ln24_fu_190_p2 = (icmp_ln25_fu_166_p2 | icmp_ln24_fu_160_p2);

assign prod_fu_96_p1 = 53'd1884600986;

assign r_fu_196_p3 = ((or_ln24_fu_190_p2[0:0] == 1'b1) ? select_ln24_fu_182_p3 : trunc_ln26_7_fu_172_p4);

assign select_ln24_fu_182_p3 = ((icmp_ln24_fu_160_p2[0:0] == 1'b1) ? 8'd127 : 8'd128);

assign sext_ln26_fu_225_p1 = $signed(trunc_ln_fu_216_p4);

assign sum_fu_135_p2 = (prod_reg_271 + 53'd137438953472);

assign tmp_fu_150_p4 = {{sum_fu_135_p2[52:45]}};

assign trunc_ln20_6_fu_140_p4 = {{sum_fu_135_p2[52:38]}};

assign trunc_ln26_7_fu_172_p4 = {{sum_fu_135_p2[45:38]}};

assign trunc_ln_fu_216_p1 = grp_fu_236_p3;

assign trunc_ln_fu_216_p4 = {{trunc_ln_fu_216_p1[16:15]}};

assign zext_ln277_fu_121_p1 = ap_sig_allocacmp_i_2;

always @ (posedge ap_clk) begin
    zext_ln277_reg_256[63:9] <= 55'b0000000000000000000000000000000000000000000000000000000;
    zext_ln277_reg_256_pp0_iter1_reg[63:9] <= 55'b0000000000000000000000000000000000000000000000000000000;
    zext_ln277_reg_256_pp0_iter2_reg[63:9] <= 55'b0000000000000000000000000000000000000000000000000000000;
    zext_ln277_reg_256_pp0_iter3_reg[63:9] <= 55'b0000000000000000000000000000000000000000000000000000000;
    zext_ln277_reg_256_pp0_iter4_reg[63:9] <= 55'b0000000000000000000000000000000000000000000000000000000;
    zext_ln277_reg_256_pp0_iter5_reg[63:9] <= 55'b0000000000000000000000000000000000000000000000000000000;
end

endmodule //awn_forward_awn_forward_Pipeline_VITIS_LOOP_277_11
