// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module awn_forward_u_branch (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        y_tanh_address0,
        y_tanh_ce0,
        y_tanh_we0,
        y_tanh_d0
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [11:0] y_tanh_address0;
output   y_tanh_ce0;
output   y_tanh_we0;
output  [0:0] y_tanh_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [11:0] tmp_fu_90_p3;
reg   [11:0] tmp_reg_124;
wire    ap_CS_fsm_state3;
wire    grp_u_branch_Pipeline_VITIS_LOOP_117_6_fu_34_ap_start;
wire    grp_u_branch_Pipeline_VITIS_LOOP_117_6_fu_34_ap_done;
wire    grp_u_branch_Pipeline_VITIS_LOOP_117_6_fu_34_ap_idle;
wire    grp_u_branch_Pipeline_VITIS_LOOP_117_6_fu_34_ap_ready;
wire   [11:0] grp_u_branch_Pipeline_VITIS_LOOP_117_6_fu_34_y_tanh_address0;
wire    grp_u_branch_Pipeline_VITIS_LOOP_117_6_fu_34_y_tanh_ce0;
wire    grp_u_branch_Pipeline_VITIS_LOOP_117_6_fu_34_y_tanh_we0;
wire   [0:0] grp_u_branch_Pipeline_VITIS_LOOP_117_6_fu_34_y_tanh_d0;
reg    grp_u_branch_Pipeline_VITIS_LOOP_117_6_fu_34_ap_start_reg;
wire   [0:0] icmp_ln116_fu_78_p2;
wire    ap_CS_fsm_state4;
reg   [6:0] oc_fu_26;
wire   [6:0] add_ln100_fu_55_p2;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln100_fu_49_p2;
reg   [6:0] oc_1_fu_30;
wire   [6:0] add_ln116_fu_84_p2;
wire   [5:0] trunc_ln116_fu_74_p1;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 grp_u_branch_Pipeline_VITIS_LOOP_117_6_fu_34_ap_start_reg = 1'b0;
#0 oc_fu_26 = 7'd0;
#0 oc_1_fu_30 = 7'd0;
end

awn_forward_u_branch_Pipeline_VITIS_LOOP_117_6 grp_u_branch_Pipeline_VITIS_LOOP_117_6_fu_34(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_u_branch_Pipeline_VITIS_LOOP_117_6_fu_34_ap_start),
    .ap_done(grp_u_branch_Pipeline_VITIS_LOOP_117_6_fu_34_ap_done),
    .ap_idle(grp_u_branch_Pipeline_VITIS_LOOP_117_6_fu_34_ap_idle),
    .ap_ready(grp_u_branch_Pipeline_VITIS_LOOP_117_6_fu_34_ap_ready),
    .zext_ln126(tmp_reg_124),
    .y_tanh_address0(grp_u_branch_Pipeline_VITIS_LOOP_117_6_fu_34_y_tanh_address0),
    .y_tanh_ce0(grp_u_branch_Pipeline_VITIS_LOOP_117_6_fu_34_y_tanh_ce0),
    .y_tanh_we0(grp_u_branch_Pipeline_VITIS_LOOP_117_6_fu_34_y_tanh_we0),
    .y_tanh_d0(grp_u_branch_Pipeline_VITIS_LOOP_117_6_fu_34_y_tanh_d0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_u_branch_Pipeline_VITIS_LOOP_117_6_fu_34_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln116_fu_78_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
            grp_u_branch_Pipeline_VITIS_LOOP_117_6_fu_34_ap_start_reg <= 1'b1;
        end else if ((grp_u_branch_Pipeline_VITIS_LOOP_117_6_fu_34_ap_ready == 1'b1)) begin
            grp_u_branch_Pipeline_VITIS_LOOP_117_6_fu_34_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln100_fu_49_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        oc_1_fu_30 <= 7'd0;
    end else if (((icmp_ln116_fu_78_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        oc_1_fu_30 <= add_ln116_fu_84_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        oc_fu_26 <= 7'd0;
    end else if (((icmp_ln100_fu_49_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        oc_fu_26 <= add_ln100_fu_55_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        tmp_reg_124[11 : 6] <= tmp_fu_90_p3[11 : 6];
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_u_branch_Pipeline_VITIS_LOOP_117_6_fu_34_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((icmp_ln116_fu_78_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln116_fu_78_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln100_fu_49_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((icmp_ln116_fu_78_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((grp_u_branch_Pipeline_VITIS_LOOP_117_6_fu_34_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln100_fu_55_p2 = (oc_fu_26 + 7'd1);

assign add_ln116_fu_84_p2 = (oc_1_fu_30 + 7'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign grp_u_branch_Pipeline_VITIS_LOOP_117_6_fu_34_ap_start = grp_u_branch_Pipeline_VITIS_LOOP_117_6_fu_34_ap_start_reg;

assign icmp_ln100_fu_49_p2 = ((oc_fu_26 == 7'd64) ? 1'b1 : 1'b0);

assign icmp_ln116_fu_78_p2 = ((oc_1_fu_30 == 7'd64) ? 1'b1 : 1'b0);

assign tmp_fu_90_p3 = {{trunc_ln116_fu_74_p1}, {6'd0}};

assign trunc_ln116_fu_74_p1 = oc_1_fu_30[5:0];

assign y_tanh_address0 = grp_u_branch_Pipeline_VITIS_LOOP_117_6_fu_34_y_tanh_address0;

assign y_tanh_ce0 = grp_u_branch_Pipeline_VITIS_LOOP_117_6_fu_34_y_tanh_ce0;

assign y_tanh_d0 = grp_u_branch_Pipeline_VITIS_LOOP_117_6_fu_34_y_tanh_d0;

assign y_tanh_we0 = grp_u_branch_Pipeline_VITIS_LOOP_117_6_fu_34_y_tanh_we0;

always @ (posedge ap_clk) begin
    tmp_reg_124[5:0] <= 6'b000000;
end

endmodule //awn_forward_u_branch
