-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity awn_forward_conv2_block_p_ZL2W2_4_37_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of awn_forward_conv2_block_p_ZL2W2_4_37_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00010101", 1 => "00000010", 2 => "00010010", 3 => "00000111", 
    4 => "00000001", 5 => "00001000", 6 => "11110011", 7 => "00000011", 
    8 => "11100111", 9 => "00001010", 10 => "00011111", 11 => "00100000", 
    12 => "00000110", 13 => "11111101", 14 => "00001111", 15 => "00010110", 
    16 => "11111101", 17 => "00100010", 18 => "11111011", 19 => "00000000", 
    20 => "11100111", 21 => "00000000", 22 => "11110010", 23 => "00000010", 
    24 => "00111001", 25 => "00010011", 26 => "00001011", 27 => "11100001", 
    28 => "11110100", 29 => "00001100", 30 => "00100010", 31 => "00001110", 
    32 => "11110110", 33 => "11011001", 34 => "11001010", 35 => "00000100", 
    36 => "11110101", 37 => "10111101", 38 => "11110010", 39 => "00011011", 
    40 => "00001111", 41 => "00010100", 42 => "11011110", 43 => "11101011", 
    44 => "00011110", 45 => "11110000", 46 => "11110000", 47 => "00000010", 
    48 => "00001111", 49 => "00000110", 50 => "00001101", 51 => "11101110", 
    52 => "11101101", 53 => "11111100", 54 => "11101010", 55 => "00001010", 
    56 => "00011100", 57 => "00000010", 58 => "00010100", 59 => "11010101", 
    60 => "00001010", 61 => "00000101", 62 => "00000101", 63 => "11110010");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

