-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity awn_forward_linear_acc_32_128_Pipeline_VITIS_LOOP_186_1_p_ZL4Wse0_54_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of awn_forward_linear_acc_32_128_Pipeline_VITIS_LOOP_186_1_p_ZL4Wse0_54_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "11001100", 1 => "10101110", 2 => "11101100", 3 => "00100001", 
    4 => "00101001", 5 => "11011110", 6 => "00000001", 7 => "11011001", 
    8 => "11000111", 9 => "11001100", 10 => "11111001", 11 => "11010101", 
    12 => "00000111", 13 => "11101101", 14 => "00001101", 15 => "11011011", 
    16 => "11001011", 17 => "00100010", 18 => "11010101", 19 => "00110101", 
    20 => "00000000", 21 => "00001101", 22 => "11100100", 23 => "00000110", 
    24 => "00010101", 25 => "00000111", 26 => "00011001", 27 => "00000100", 
    28 => "11010111", 29 => "00011110", 30 => "00110101", 31 => "11010111");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

