-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity awn_forward_conv2_block_p_ZL2W2_0_36_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 7; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of awn_forward_conv2_block_p_ZL2W2_0_36_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "1110111", 1 => "1011011", 2 => "0011101", 3 => "0000110", 
    4 => "1010111", 5 => "1010101", 6 => "0100110", 7 => "1110010", 
    8 => "0000100", 9 => "0001010", 10 => "0111101", 11 => "1011001", 
    12 => "1110110", 13 => "1001110", 14 => "0000100", 15 => "0000110", 
    16 => "1101101", 17 => "1111010", 18 => "0000001", 19 => "1111011", 
    20 => "0001000", 21 => "1110110", 22 => "0010111", 23 => "1111110", 
    24 => "0001100", 25 => "1110101", 26 => "1111011", 27 => "0010101", 
    28 => "1011011", 29 => "1111111", 30 => "0001001", 31 => "1111100", 
    32 => "0000110", 33 => "0011100", 34 => "0100111", 35 => "1001111", 
    36 => "1111111", 37 => "1010100", 38 => "0010000", 39 => "0110100", 
    40 => "1111100", 41 => "0001110", 42 => "1110010", 43 => "1110110", 
    44 => "1000110", 45 => "1110000", 46 => "1101101", 47 => "1110111", 
    48 => "1111110", 49 => "0000111", 50 => "1111111", 51 => "0010101", 
    52 => "1000010", 53 => "0001110", 54 => "1111100", 55 => "1111000", 
    56 => "0101101", 57 => "0011101", 58 => "1111000", 59 => "1111011", 
    60 => "1100000", 61 => "0010101", 62 => "1010011", 63 => "0000111");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

