-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity awn_forward_conv2_block_p_ZL2W2_2_27_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 7; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of awn_forward_conv2_block_p_ZL2W2_2_27_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "1101110", 1 => "0001100", 2 => "1110000", 3 => "1110110", 
    4 => "0001000", 5 => "1110110", 6 => "1111000", 7 => "0001001", 
    8 => "0101110", 9 => "0001101", 10 => "0100000", 11 => "0001000", 
    12 => "1011111", 13 => "1110001", 14 => "1100101", 15 => "0001011", 
    16 => "0011011", 17 => "1011000", 18 => "1001000", 19 => "1110111", 
    20 => "0010101", 21 => "0001011", 22 => "0000000", 23 => "1111110", 
    24 => "0011101", 25 => "1101011", 26 => "0000101", 27 => "1100101", 
    28 => "0000010", 29 => "0011001", 30 => "1010011", 31 => "0010111", 
    32 => "1110110", 33 => "1110001", 34 => "1100001", 35 => "0010110", 
    36 => "0000100", 37 => "0000110", 38 => "1110011", 39 => "1101100", 
    40 => "0010000", 41 => "0000001", 42 => "0001100", 43 => "0000111", 
    44 => "0001101", 45 => "1111000", 46 => "0001111", 47 => "1110101", 
    48 => "0011011", 49 => "1101111", 50 => "0000000", 51 => "1101011", 
    52 => "1000110", 53 => "0101110", 54 => "1101000", 55 => "0011101", 
    56 => "1010010", 57 => "0100010", 58 => "0001000", 59 => "1100111", 
    60 => "0000000", 61 => "1100011", 62 => "0000111", 63 => "0011110");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

