-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity awn_forward_conv2_block_p_ZL2W2_4_62_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of awn_forward_conv2_block_p_ZL2W2_4_62_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00100010", 1 => "00010000", 2 => "00001111", 3 => "00101010", 
    4 => "00001000", 5 => "11100100", 6 => "00001110", 7 => "11111011", 
    8 => "00011011", 9 => "11110010", 10 => "11001111", 11 => "00100000", 
    12 => "00100000", 13 => "00010011", 14 => "00001111", 15 => "00100010", 
    16 => "11010011", 17 => "00000101", 18 => "11110110", 19 => "00000101", 
    20 => "00010000", 21 => "00000010", 22 => "11110011", 23 => "00000101", 
    24 => "00001111", 25 => "00010011", 26 => "11110101", 27 => "11001000", 
    28 => "11110101", 29 => "00001101", 30 => "00000100", 31 => "00100000", 
    32 => "00001011", 33 => "00000010", 34 => "11101111", 35 => "00101101", 
    36 => "00010011", 37 => "11001111", 38 => "11110101", 39 => "00000100", 
    40 => "00000101", 41 => "00000101", 42 => "11111000", 43 => "11110010", 
    44 => "00101110", 45 => "01010111", 46 => "10011110", 47 => "00000100", 
    48 => "11011100", 49 => "00010001", 50 => "00010110", 51 => "11111110", 
    52 => "11100110", 53 => "00110000", 54 => "00010111", 55 => "00010010", 
    56 => "00011000", 57 => "00010110", 58 => "11111111", 59 => "00001001", 
    60 => "00010001", 61 => "11111111", 62 => "11000000", 63 => "00010010");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

