-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity awn_forward_conv2_block_p_ZL2W2_3_61_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of awn_forward_conv2_block_p_ZL2W2_3_61_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00010111", 1 => "00001000", 2 => "11110000", 3 => "01000011", 
    4 => "11111101", 5 => "11101111", 6 => "11111010", 7 => "11110011", 
    8 => "11110111", 9 => "11101100", 10 => "11010100", 11 => "11101011", 
    12 => "00010010", 13 => "11111001", 14 => "00000100", 15 => "00000000", 
    16 => "11100000", 17 => "11011011", 18 => "00000110", 19 => "00010010", 
    20 => "11110010", 21 => "11110000", 22 => "00010110", 23 => "11111010", 
    24 => "00011100", 25 => "00001111", 26 => "11111011", 27 => "11110010", 
    28 => "00000010", 29 => "11110000", 30 => "11110101", 31 => "11110111", 
    32 => "11110111", 33 => "11111110", 34 => "11101001", 35 => "00011111", 
    36 => "00011011", 37 => "00001111", 38 => "11111000", 39 => "00000001", 
    40 => "11110111", 41 => "00011010", 42 => "00000000", 43 => "00000011", 
    44 => "00011001", 45 => "11111111", 46 => "00010111", 47 => "00010011", 
    48 => "11110111", 49 => "11111010", 50 => "11111011", 51 => "11111111", 
    52 => "11101100", 53 => "00000011", 54 => "00011101", 55 => "00010101", 
    56 => "11101000", 57 => "11110000", 58 => "11101111", 59 => "11010010", 
    60 => "00000110", 61 => "00010011", 62 => "11110110", 63 => "00101001");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

