-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity awn_forward_conv2_block_p_ZL2W2_1_57_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 7; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of awn_forward_conv2_block_p_ZL2W2_1_57_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "1111010", 1 => "1111101", 2 => "1111111", 3 => "1111001", 
    4 => "0010110", 5 => "1110110", 6 => "1110000", 7 => "1111100", 
    8 => "0001110", 9 => "0000101", 10 => "1111001", 11 => "1101010", 
    12 => "1110000", 13 => "0000110", 14 => "1100110", 15 => "0000011", 
    16 => "0110101", 17 => "1100000", 18 => "1101111", 19 => "1111100", 
    20 => "0001101", 21 => "1100111", 22 => "0010100", 23 => "1100111", 
    24 => "0001110", 25 => "1110010", 26 => "1011101", 27 => "1111010", 
    28 => "0000111", 29 => "0001111", 30 => "0001001", 31 => "0011000", 
    32 => "1101111", 33 => "0001000", 34 => "1101010", 35 => "1111001", 
    36 => "0000111", 37 => "0000001", 38 => "1110001", 39 => "1011111", 
    40 => "1111011", 41 => "1111110", 42 => "1111100", 43 => "1111100", 
    44 => "0001101", 45 => "0011001", 46 => "1110010", 47 => "0000110", 
    48 => "0000101", 49 => "0001101", 50 => "0010101", 51 => "1110011", 
    52 => "1101100", 53 => "0011000", 54 => "0000101", 55 => "0011101", 
    56 => "1101011", 57 => "0010010", 58 => "1110000", 59 => "1101101", 
    60 => "1110110", 61 => "1101111", 62 => "1111010", 63 => "0010010");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

