-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity awn_forward_conv2_block_p_ZL2W2_2_59_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 7; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of awn_forward_conv2_block_p_ZL2W2_2_59_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "1010001", 1 => "0001011", 2 => "1111100", 3 => "0001001", 
    4 => "0101000", 5 => "0001001", 6 => "1111111", 7 => "1111000", 
    8 => "0001101", 9 => "0001111", 10 => "0000010", 11 => "0001100", 
    12 => "1111100", 13 => "0001001", 14 => "1110111", 15 => "1111101", 
    16 => "1111010", 17 => "1100110", 18 => "1110101", 19 => "0000100", 
    20 => "0000101", 21 => "1110110", 22 => "1111100", 23 => "1110010", 
    24 => "1101010", 25 => "0000101", 26 => "0001010", 27 => "0000001", 
    28 => "1110001", 29 => "0001000", 30 => "0011000", 31 => "0100000", 
    32 => "1110110", 33 => "1111000", 34 => "1101110", 35 => "0000110", 
    36 => "0000101", 37 => "0000011", 38 => "1111100", 39 => "1010110", 
    40 => "1111100", 41 => "1111100", 42 => "1110000", 43 => "0010110", 
    44 => "0010010", 45 => "0011100", 46 => "1101001", 47 => "1110111", 
    48 => "0101000", 49 => "0000101", 50 => "0000001", 51 => "1110101", 
    52 => "0010001", 53 => "0001011", 54 => "0000101", 55 => "0010010", 
    56 => "1111010", 57 => "0000000", 58 => "0000110", 59 => "0100000", 
    60 => "0000111", 61 => "0010000", 62 => "1111010", 63 => "0011000");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

