-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity awn_forward_conv2_block_p_ZL2W2_3_25_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of awn_forward_conv2_block_p_ZL2W2_3_25_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00001011", 1 => "00001010", 2 => "11010101", 3 => "00001101", 
    4 => "00010110", 5 => "11101101", 6 => "00000111", 7 => "00000100", 
    8 => "00101011", 9 => "00000100", 10 => "00000100", 11 => "10111100", 
    12 => "11111011", 13 => "00000100", 14 => "11110100", 15 => "00001100", 
    16 => "00010011", 17 => "11111001", 18 => "11111011", 19 => "11111001", 
    20 => "11101110", 21 => "00000101", 22 => "00001010", 23 => "00000001", 
    24 => "11011110", 25 => "11101000", 26 => "11011001", 27 => "11110101", 
    28 => "00000001", 29 => "00001110", 30 => "11011111", 31 => "00100111", 
    32 => "11101001", 33 => "11111001", 34 => "11110110", 35 => "00001110", 
    36 => "11111001", 37 => "11101110", 38 => "11111000", 39 => "11010100", 
    40 => "00000111", 41 => "11111100", 42 => "00000001", 43 => "00000111", 
    44 => "11111111", 45 => "11010110", 46 => "00000111", 47 => "00000101", 
    48 => "00110101", 49 => "00000101", 50 => "11111110", 51 => "00001011", 
    52 => "11011000", 53 => "00011110", 54 => "11110101", 55 => "00010110", 
    56 => "11100101", 57 => "00000011", 58 => "11011001", 59 => "11000101", 
    60 => "11011010", 61 => "00000001", 62 => "11111010", 63 => "00100101");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

