-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity awn_forward_conv2_block_p_ZL2W2_1_38_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of awn_forward_conv2_block_p_ZL2W2_1_38_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "11110101", 1 => "11101110", 2 => "00010100", 3 => "00000111", 
    4 => "11110011", 5 => "11101001", 6 => "00000101", 7 => "00010011", 
    8 => "00001111", 9 => "00010010", 10 => "10110100", 11 => "00010100", 
    12 => "11110110", 13 => "11111100", 14 => "00000010", 15 => "11100010", 
    16 => "00001100", 17 => "11101011", 18 => "11110110", 19 => "11101010", 
    20 => "00010001", 21 => "00001011", 22 => "00011110", 23 => "00001101", 
    24 => "00001111", 25 => "11110100", 26 => "00010100", 27 => "00001101", 
    28 => "00001111", 29 => "11111100", 30 => "00110000", 31 => "00010101", 
    32 => "11111111", 33 => "00001111", 34 => "00001111", 35 => "11100111", 
    36 => "11110011", 37 => "11110010", 38 => "00001001", 39 => "11110011", 
    40 => "00101001", 41 => "00011000", 42 => "00010101", 43 => "11111001", 
    44 => "00010011", 45 => "00011000", 46 => "00001111", 47 => "11110111", 
    48 => "00100011", 49 => "00010001", 50 => "00001111", 51 => "11110001", 
    52 => "00011111", 53 => "00010100", 54 => "00011100", 55 => "00011100", 
    56 => "00000011", 57 => "11101110", 58 => "00101001", 59 => "00010000", 
    60 => "11111101", 61 => "11111111", 62 => "11110001", 63 => "00001110");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

