-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity awn_forward_conv2_block_p_ZL2W2_4_35_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of awn_forward_conv2_block_p_ZL2W2_4_35_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00000011", 1 => "11111010", 2 => "00011011", 3 => "11101111", 
    4 => "00000000", 5 => "00100111", 6 => "11100111", 7 => "00100001", 
    8 => "00000001", 9 => "00011110", 10 => "00100000", 11 => "00000100", 
    12 => "11101100", 13 => "11111001", 14 => "00000001", 15 => "11110100", 
    16 => "00001101", 17 => "01010010", 18 => "11110011", 19 => "11111000", 
    20 => "11110000", 21 => "11101011", 22 => "11010011", 23 => "00010101", 
    24 => "00110101", 25 => "00000111", 26 => "00010111", 27 => "11101101", 
    28 => "00001010", 29 => "00110101", 30 => "00000010", 31 => "11001100", 
    32 => "00001101", 33 => "11010000", 34 => "11100100", 35 => "11000000", 
    36 => "11101010", 37 => "11110000", 38 => "00001010", 39 => "01000111", 
    40 => "00010011", 41 => "11110001", 42 => "11110111", 43 => "11011101", 
    44 => "00001001", 45 => "00011101", 46 => "00011000", 47 => "11111010", 
    48 => "11010110", 49 => "00000001", 50 => "00101000", 51 => "00011001", 
    52 => "11011111", 53 => "00001010", 54 => "11110011", 55 => "11101110", 
    56 => "00010001", 57 => "11001001", 58 => "11110110", 59 => "11010001", 
    60 => "11110110", 61 => "10110100", 62 => "00100100", 63 => "11000101");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

