-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity awn_forward_conv2_block_p_ZL2W2_3_12_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 7; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of awn_forward_conv2_block_p_ZL2W2_3_12_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "0010110", 1 => "0000011", 2 => "1110011", 3 => "1111010", 
    4 => "1110010", 5 => "1111010", 6 => "0000010", 7 => "0001011", 
    8 => "1101100", 9 => "0000101", 10 => "0010100", 11 => "1101011", 
    12 => "0000000", 13 => "1110101", 14 => "1111001", 15 => "0011010", 
    16 => "0010001", 17 => "1111000", 18 => "1110111", 19 => "0001000", 
    20 => "1110101", 21 => "0001110", 22 => "0000010", 23 => "0000001", 
    24 => "0001101", 25 => "0000001", 26 => "0001011", 27 => "1111011", 
    28 => "0001101", 29 => "1100011", 30 => "1011110", 31 => "0011100", 
    32 => "1101000", 33 => "0010000", 34 => "1111100", 35 => "1101101", 
    36 => "1111111", 37 => "0000111", 38 => "1111101", 39 => "1101000", 
    40 => "1111100", 41 => "1110011", 42 => "0001000", 43 => "1110100", 
    44 => "0000000", 45 => "1111011", 46 => "0011011", 47 => "0010101", 
    48 => "0011101", 49 => "0010010", 50 => "1110010", 51 => "1111100", 
    52 => "1100110", 53 => "1110101", 54 => "1111111", 55 => "0011110", 
    56 => "1110110", 57 => "0010111", 58 => "1110101", 59 => "1010100", 
    60 => "1111110", 61 => "0001000", 62 => "0000010", 63 => "0010111");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

