-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity awn_forward_conv2_block_p_ZL2W2_1_40_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 7; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of awn_forward_conv2_block_p_ZL2W2_1_40_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "1101100", 1 => "0011110", 2 => "1101100", 3 => "0011001", 
    4 => "1111111", 5 => "1100101", 6 => "1111010", 7 => "0001110", 
    8 => "1110100", 9 => "1111001", 10 => "0100000", 11 => "1111001", 
    12 => "0000001", 13 => "0011111", 14 => "0000100", 15 => "0011011", 
    16 => "0000010", 17 => "0001111", 18 => "1111100", 19 => "0001101", 
    20 => "0010001", 21 => "0010100", 22 => "1111000", 23 => "1111100", 
    24 => "1111010", 25 => "1110100", 26 => "0011011", 27 => "0000001", 
    28 => "0011011", 29 => "1111011", 30 => "0011011", 31 => "0001011", 
    32 => "1111000", 33 => "0001001", 34 => "1101000", 35 => "0000100", 
    36 => "1011010", 37 => "1111110", 38 => "0000001", 39 => "0010100", 
    40 => "0010011", 41 => "1010101", 42 => "0010011", 43 => "1110101", 
    44 => "0100001", 45 => "0011111", 46 => "0101111", 47 => "0010100", 
    48 => "0001110", 49 => "0010110", 50 => "0000000", 51 => "0000000", 
    52 => "1100010", 53 => "1101111", 54 => "1110100", 55 => "0101111", 
    56 => "0001101", 57 => "1111000", 58 => "1101010", 59 => "1101000", 
    60 => "0000101", 61 => "1110001", 62 => "1111000", 63 => "1110100");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

