-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity awn_forward_conv2_block_p_ZL2W2_1_55_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 7; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of awn_forward_conv2_block_p_ZL2W2_1_55_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "1110101", 1 => "0011001", 2 => "0000011", 3 => "1110101", 
    4 => "0001100", 5 => "0000101", 6 => "0000010", 7 => "1100101", 
    8 => "0001101", 9 => "0000001", 10 => "1111000", 11 => "0011100", 
    12 => "1111110", 13 => "0100011", 14 => "1101100", 15 => "0010100", 
    16 => "1011001", 17 => "1010111", 18 => "0000100", 19 => "1111110", 
    20 => "1111111", 21 => "1111100", 22 => "1111110", 23 => "1111011", 
    24 => "1001101", 25 => "0010000", 26 => "0010000", 27 => "1110110", 
    28 => "1111010", 29 => "0000111", 30 => "0001101", 31 => "0100000", 
    32 => "1101101", 33 => "0000011", 34 => "1101000", 35 => "1111011", 
    36 => "1110011", 37 => "1110001", 38 => "1101110", 39 => "1100100", 
    40 => "1111001", 41 => "1101000", 42 => "0000001", 43 => "0000110", 
    44 => "0000000", 45 => "0101001", 46 => "0001001", 47 => "1111101", 
    48 => "0011101", 49 => "0001111", 50 => "0000001", 51 => "1110010", 
    52 => "0011001", 53 => "0100101", 54 => "1101010", 55 => "0001110", 
    56 => "1110100", 57 => "1100110", 58 => "0001010", 59 => "0100011", 
    60 => "0000111", 61 => "0001101", 62 => "0000000", 63 => "0010000");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

