-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity awn_forward_conv2_block_p_ZL2W2_0_34_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of awn_forward_conv2_block_p_ZL2W2_0_34_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00001001", 1 => "11110110", 2 => "11101001", 3 => "00000100", 
    4 => "00000100", 5 => "11111100", 6 => "00001111", 7 => "00101010", 
    8 => "11101110", 9 => "11111110", 10 => "00000111", 11 => "11011010", 
    12 => "00000111", 13 => "00000111", 14 => "00001101", 15 => "00000101", 
    16 => "00000100", 17 => "11101101", 18 => "00001010", 19 => "00010110", 
    20 => "00010001", 21 => "00010110", 22 => "00000001", 23 => "00010011", 
    24 => "11011100", 25 => "00011111", 26 => "00101110", 27 => "11110100", 
    28 => "11101111", 29 => "00000010", 30 => "11110111", 31 => "00000011", 
    32 => "00010000", 33 => "00011001", 34 => "11100100", 35 => "00010111", 
    36 => "11111010", 37 => "00110100", 38 => "11111110", 39 => "10101110", 
    40 => "00010110", 41 => "00000101", 42 => "11111000", 43 => "00010110", 
    44 => "11001010", 45 => "11110010", 46 => "11111100", 47 => "00001110", 
    48 => "00000110", 49 => "00011000", 50 => "00000010", 51 => "11111010", 
    52 => "11100100", 53 => "00000110", 54 => "00100010", 55 => "11011001", 
    56 => "00000000", 57 => "11100100", 58 => "00011001", 59 => "00000000", 
    60 => "00101110", 61 => "00000011", 62 => "00000000", 63 => "00111110");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

