-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity awn_forward_conv2_block_p_ZL2W2_2_10_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of awn_forward_conv2_block_p_ZL2W2_2_10_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "11110110", 1 => "00001011", 2 => "00000010", 3 => "01001001", 
    4 => "00000011", 5 => "11110100", 6 => "00110001", 7 => "00000111", 
    8 => "11110010", 9 => "00000001", 10 => "00001011", 11 => "00000011", 
    12 => "00000100", 13 => "00011101", 14 => "00000111", 15 => "00001001", 
    16 => "11010010", 17 => "00010101", 18 => "11110010", 19 => "11110100", 
    20 => "00000100", 21 => "11100110", 22 => "00011110", 23 => "11110000", 
    24 => "11010111", 25 => "00001111", 26 => "00100010", 27 => "00000000", 
    28 => "11111100", 29 => "00000001", 30 => "00001111", 31 => "11101010", 
    32 => "11101011", 33 => "00101111", 34 => "11111011", 35 => "00101001", 
    36 => "11101111", 37 => "11010100", 38 => "11111101", 39 => "00010011", 
    40 => "11111101", 41 => "11111101", 42 => "00000110", 43 => "00010001", 
    44 => "00100110", 45 => "00001010", 46 => "00100001", 47 => "11111111", 
    48 => "11100110", 49 => "00010011", 50 => "11111001", 51 => "00001011", 
    52 => "00000001", 53 => "11111110", 54 => "00011110", 55 => "11110101", 
    56 => "00010011", 57 => "00000110", 58 => "11111010", 59 => "11111011", 
    60 => "00010000", 61 => "00011010", 62 => "11111010", 63 => "11111100");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

