-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity awn_forward_conv2_block_p_ZL2W2_2_31_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 7; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of awn_forward_conv2_block_p_ZL2W2_2_31_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "1110000", 1 => "1111110", 2 => "1111100", 3 => "1101101", 
    4 => "1111001", 5 => "0000110", 6 => "1111110", 7 => "1100011", 
    8 => "0000110", 9 => "0000111", 10 => "1101001", 11 => "0100001", 
    12 => "1111010", 13 => "0000001", 14 => "1110111", 15 => "0100010", 
    16 => "1011010", 17 => "1101011", 18 => "1110100", 19 => "0001001", 
    20 => "0000110", 21 => "0000010", 22 => "0000000", 23 => "0011100", 
    24 => "1010111", 25 => "0001010", 26 => "1111101", 27 => "1100100", 
    28 => "0001000", 29 => "0000111", 30 => "0010000", 31 => "0011000", 
    32 => "1111100", 33 => "0000111", 34 => "0001011", 35 => "0000100", 
    36 => "1111100", 37 => "1111111", 38 => "0000100", 39 => "1001000", 
    40 => "0100110", 41 => "1111100", 42 => "0000101", 43 => "0000101", 
    44 => "1110001", 45 => "0110110", 46 => "1110000", 47 => "1101110", 
    48 => "0111000", 49 => "1111111", 50 => "1101010", 51 => "1111101", 
    52 => "0011001", 53 => "0011000", 54 => "1101111", 55 => "0001111", 
    56 => "1101010", 57 => "1011000", 58 => "0001010", 59 => "0101100", 
    60 => "0001011", 61 => "0001000", 62 => "0000001", 63 => "0011111");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

