-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity awn_forward_conv2_block_p_ZL2W2_1_2_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 7; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of awn_forward_conv2_block_p_ZL2W2_1_2_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "0010000", 1 => "0000011", 2 => "1001111", 3 => "1111000", 
    4 => "1111111", 5 => "0001111", 6 => "1111010", 7 => "0101001", 
    8 => "0001010", 9 => "1110100", 10 => "0001101", 11 => "0000111", 
    12 => "0001000", 13 => "0000111", 14 => "0010000", 15 => "0000001", 
    16 => "0011001", 17 => "1001010", 18 => "0011011", 19 => "0001110", 
    20 => "1100111", 21 => "0010010", 22 => "0000010", 23 => "1111111", 
    24 => "0000101", 25 => "1111100", 26 => "0000110", 27 => "1100111", 
    28 => "0001011", 29 => "0001111", 30 => "1110011", 31 => "1010110", 
    32 => "0001001", 33 => "0000010", 34 => "0010001", 35 => "1111110", 
    36 => "0000111", 37 => "0001010", 38 => "0000100", 39 => "0010111", 
    40 => "0001111", 41 => "0011000", 42 => "0001010", 43 => "1101000", 
    44 => "1100100", 45 => "1010100", 46 => "1111001", 47 => "0000001", 
    48 => "1010001", 49 => "0010110", 50 => "1011110", 51 => "1111011", 
    52 => "0101000", 53 => "1111100", 54 => "1111100", 55 => "1111001", 
    56 => "0101101", 57 => "0011101", 58 => "0110010", 59 => "1111100", 
    60 => "0001010", 61 => "0000001", 62 => "0011010", 63 => "0100101");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

