-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity awn_forward_conv2_block_p_ZL2W2_2_34_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 7; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of awn_forward_conv2_block_p_ZL2W2_2_34_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "1111100", 1 => "0010110", 2 => "1111001", 3 => "0011010", 
    4 => "1110111", 5 => "1110101", 6 => "1010111", 7 => "0000010", 
    8 => "0000111", 9 => "0001000", 10 => "1011100", 11 => "0000101", 
    12 => "0000000", 13 => "1111111", 14 => "0010111", 15 => "0010001", 
    16 => "0001001", 17 => "1100000", 18 => "0011101", 19 => "0011010", 
    20 => "0001101", 21 => "0100100", 22 => "0001100", 23 => "0010100", 
    24 => "0011011", 25 => "0001010", 26 => "0000100", 27 => "0001111", 
    28 => "1100011", 29 => "0000110", 30 => "0101110", 31 => "0010011", 
    32 => "0011011", 33 => "0100000", 34 => "1101010", 35 => "0010011", 
    36 => "0010010", 37 => "0010000", 38 => "0001101", 39 => "1110100", 
    40 => "0001100", 41 => "0011000", 42 => "1111100", 43 => "1011010", 
    44 => "0000100", 45 => "0010000", 46 => "1100111", 47 => "0001011", 
    48 => "0101111", 49 => "0000000", 50 => "1101001", 51 => "1101111", 
    52 => "1011100", 53 => "0001000", 54 => "0011110", 55 => "1110101", 
    56 => "1010101", 57 => "0001101", 58 => "0010111", 59 => "0001111", 
    60 => "0011001", 61 => "0000100", 62 => "0000011", 63 => "0000011");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

