-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity awn_forward_conv2_block_p_ZL2W2_2_1_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 7; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of awn_forward_conv2_block_p_ZL2W2_2_1_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "0000010", 1 => "0011110", 2 => "1110100", 3 => "0001010", 
    4 => "0000010", 5 => "1110111", 6 => "1100100", 7 => "0010011", 
    8 => "1111111", 9 => "1111100", 10 => "0101010", 11 => "1110001", 
    12 => "0001010", 13 => "0010101", 14 => "0010101", 15 => "0010000", 
    16 => "1110001", 17 => "1100010", 18 => "0010010", 19 => "1111011", 
    20 => "0001111", 21 => "1111000", 22 => "0001110", 23 => "0000110", 
    24 => "0001001", 25 => "0001001", 26 => "0111001", 27 => "1111101", 
    28 => "1110010", 29 => "1110111", 30 => "0000011", 31 => "1111110", 
    32 => "1101111", 33 => "0001000", 34 => "1110011", 35 => "0101100", 
    36 => "1111011", 37 => "1101010", 38 => "1100110", 39 => "1001100", 
    40 => "1101011", 41 => "0000111", 42 => "0000011", 43 => "0011000", 
    44 => "1111111", 45 => "1110010", 46 => "0010010", 47 => "0001010", 
    48 => "0010000", 49 => "0100101", 50 => "0011001", 51 => "1100010", 
    52 => "1010010", 53 => "0000110", 54 => "0101100", 55 => "0011111", 
    56 => "1110101", 57 => "0011101", 58 => "0100100", 59 => "1110011", 
    60 => "0010101", 61 => "0000000", 62 => "1101110", 63 => "0001010");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

