-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity awn_forward_conv2_block_p_ZL2W2_4_2_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of awn_forward_conv2_block_p_ZL2W2_4_2_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00100011", 1 => "11111111", 2 => "00001100", 3 => "00010001", 
    4 => "00010111", 5 => "00100000", 6 => "11110001", 7 => "00011011", 
    8 => "00001100", 9 => "11111100", 10 => "11101100", 11 => "00011111", 
    12 => "00010101", 13 => "00001100", 14 => "00010101", 15 => "00100010", 
    16 => "00000101", 17 => "00011001", 18 => "11110101", 19 => "11111110", 
    20 => "11000110", 21 => "00000001", 22 => "11100011", 23 => "00000101", 
    24 => "00110010", 25 => "00010100", 26 => "00010101", 27 => "11011101", 
    28 => "11011100", 29 => "11111110", 30 => "00010010", 31 => "11111110", 
    32 => "00010011", 33 => "10100011", 34 => "11001110", 35 => "11110101", 
    36 => "00000010", 37 => "11001110", 38 => "11000111", 39 => "00100100", 
    40 => "00001111", 41 => "00110010", 42 => "10110100", 43 => "10101010", 
    44 => "00101011", 45 => "11100011", 46 => "11100110", 47 => "00001001", 
    48 => "11100010", 49 => "00000111", 50 => "00100011", 51 => "11100011", 
    52 => "00001101", 53 => "11111011", 54 => "11001111", 55 => "11110011", 
    56 => "00010100", 57 => "00001000", 58 => "00010001", 59 => "11101110", 
    60 => "11111101", 61 => "11110111", 62 => "00100001", 63 => "11111010");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

