-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity awn_forward_conv2_block_p_ZL2W2_4_17_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 7; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of awn_forward_conv2_block_p_ZL2W2_4_17_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "1010100", 1 => "1101011", 2 => "0001010", 3 => "0011000", 
    4 => "0000010", 5 => "0010000", 6 => "0000010", 7 => "0110101", 
    8 => "0000001", 9 => "0010001", 10 => "0111110", 11 => "0001011", 
    12 => "0000000", 13 => "1110111", 14 => "1110110", 15 => "0001001", 
    16 => "0010001", 17 => "0000100", 18 => "1111100", 19 => "1101010", 
    20 => "1101111", 21 => "1110000", 22 => "1101011", 23 => "0001101", 
    24 => "0011101", 25 => "1101111", 26 => "1111100", 27 => "0010010", 
    28 => "1101010", 29 => "0001100", 30 => "1010100", 31 => "0001111", 
    32 => "0101011", 33 => "1000100", 34 => "0000011", 35 => "1111111", 
    36 => "0001010", 37 => "1101101", 38 => "1111001", 39 => "0001111", 
    40 => "0010000", 41 => "1111100", 42 => "1100111", 43 => "0000101", 
    44 => "0101101", 45 => "0001011", 46 => "1100110", 47 => "1100101", 
    48 => "0010000", 49 => "1101100", 50 => "0110010", 51 => "1101110", 
    52 => "1100010", 53 => "0001010", 54 => "0000001", 55 => "0000101", 
    56 => "0010000", 57 => "0000110", 58 => "1110110", 59 => "1011001", 
    60 => "1110010", 61 => "1000101", 62 => "0000011", 63 => "0001111");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

