-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity awn_forward_conv2_block_p_ZL2W2_4_28_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 7; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of awn_forward_conv2_block_p_ZL2W2_4_28_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "1010011", 1 => "1111111", 2 => "0000000", 3 => "1100010", 
    4 => "0010001", 5 => "0000001", 6 => "0000101", 7 => "1111001", 
    8 => "1111111", 9 => "0001110", 10 => "1111001", 11 => "0001000", 
    12 => "1110100", 13 => "0001111", 14 => "1100010", 15 => "0000000", 
    16 => "1001010", 17 => "0010110", 18 => "1011010", 19 => "1111101", 
    20 => "1110011", 21 => "1011101", 22 => "1111011", 23 => "1110011", 
    24 => "0000111", 25 => "1111000", 26 => "1110001", 27 => "1111000", 
    28 => "1100100", 29 => "0000011", 30 => "0010110", 31 => "0001000", 
    32 => "0011110", 33 => "1110111", 34 => "0000100", 35 => "1110010", 
    36 => "0011010", 37 => "1100011", 38 => "1111000", 39 => "0000100", 
    40 => "1110101", 41 => "0011010", 42 => "1101100", 43 => "0010000", 
    44 => "0001001", 45 => "0001010", 46 => "1101100", 47 => "1110111", 
    48 => "0010110", 49 => "0000111", 50 => "0001100", 51 => "1111000", 
    52 => "0000111", 53 => "1101001", 54 => "1101000", 55 => "1111011", 
    56 => "1110100", 57 => "1111100", 58 => "0000111", 59 => "0001110", 
    60 => "0000000", 61 => "1110110", 62 => "0000001", 63 => "0000100");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

