-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity awn_forward_conv2_block_p_ZL2W2_1_52_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 7; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of awn_forward_conv2_block_p_ZL2W2_1_52_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "0010100", 1 => "1100011", 2 => "1110101", 3 => "1101010", 
    4 => "0000010", 5 => "1111110", 6 => "0001011", 7 => "1111110", 
    8 => "1110101", 9 => "1110010", 10 => "1111110", 11 => "0010000", 
    12 => "1101110", 13 => "1111011", 14 => "0001110", 15 => "0011001", 
    16 => "1111010", 17 => "1001001", 18 => "0010100", 19 => "0001111", 
    20 => "1111110", 21 => "1111110", 22 => "1111100", 23 => "0010111", 
    24 => "1000000", 25 => "0001100", 26 => "0011000", 27 => "1111011", 
    28 => "1101010", 29 => "0000011", 30 => "1111111", 31 => "0100010", 
    32 => "0000110", 33 => "1110101", 34 => "0000011", 35 => "1011000", 
    36 => "0000101", 37 => "1110010", 38 => "1111101", 39 => "1010111", 
    40 => "0000111", 41 => "0001110", 42 => "1111011", 43 => "0001001", 
    44 => "1011101", 45 => "0101000", 46 => "1100101", 47 => "1111111", 
    48 => "0011101", 49 => "1111111", 50 => "1110010", 51 => "1110101", 
    52 => "0010101", 53 => "0010011", 54 => "1101110", 55 => "0001110", 
    56 => "0010101", 57 => "1111111", 58 => "0000100", 59 => "0011111", 
    60 => "0000011", 61 => "0001011", 62 => "0000001", 63 => "0010100");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

