-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity awn_forward_conv2_block_p_ZL2W2_0_26_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 7; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of awn_forward_conv2_block_p_ZL2W2_0_26_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "0011110", 1 => "1110000", 2 => "1100101", 3 => "1111000", 
    4 => "1101011", 5 => "0001100", 6 => "0001000", 7 => "0110001", 
    8 => "1011101", 9 => "1010110", 10 => "1101000", 11 => "1110000", 
    12 => "1110110", 13 => "1101111", 14 => "0101100", 15 => "0001101", 
    16 => "0100001", 17 => "1010010", 18 => "0011001", 19 => "1111111", 
    20 => "1011001", 21 => "1111110", 22 => "1111101", 23 => "1111100", 
    24 => "1011100", 25 => "0001010", 26 => "0000110", 27 => "1111101", 
    28 => "0001010", 29 => "1100110", 30 => "1100000", 31 => "0010100", 
    32 => "0011001", 33 => "1011100", 34 => "0001111", 35 => "0000001", 
    36 => "0001000", 37 => "1110111", 38 => "0000100", 39 => "0000110", 
    40 => "1101001", 41 => "0011100", 42 => "1111000", 43 => "0000011", 
    44 => "0010001", 45 => "0011001", 46 => "1110111", 47 => "0001000", 
    48 => "1101010", 49 => "0000000", 50 => "1010011", 51 => "0000011", 
    52 => "0100100", 53 => "1011111", 54 => "0010100", 55 => "0011011", 
    56 => "0010011", 57 => "0001001", 58 => "1111001", 59 => "0010011", 
    60 => "1111110", 61 => "0011111", 62 => "0010000", 63 => "0010000");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

