-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity awn_forward_conv2_block_p_ZL2W2_0_48_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of awn_forward_conv2_block_p_ZL2W2_0_48_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00000010", 1 => "11111011", 2 => "00001001", 3 => "00000010", 
    4 => "00000111", 5 => "00000000", 6 => "11100000", 7 => "11110111", 
    8 => "11110101", 9 => "00011001", 10 => "11010001", 11 => "00011100", 
    12 => "11111110", 13 => "00000101", 14 => "00001001", 15 => "00001001", 
    16 => "01000010", 17 => "00010101", 18 => "00101101", 19 => "00001111", 
    20 => "00000001", 21 => "00000100", 22 => "00000110", 23 => "00001100", 
    24 => "00011000", 25 => "00010100", 26 => "00001011", 27 => "11110011", 
    28 => "11110101", 29 => "11111111", 30 => "11110101", 31 => "00001010", 
    32 => "11011110", 33 => "00101001", 34 => "11101101", 35 => "11111001", 
    36 => "00010011", 37 => "00100000", 38 => "00000110", 39 => "11100010", 
    40 => "11110010", 41 => "00001000", 42 => "11110011", 43 => "00100010", 
    44 => "00010100", 45 => "00010011", 46 => "11111000", 47 => "11111110", 
    48 => "11011100", 49 => "11110011", 50 => "00000111", 51 => "10110000", 
    52 => "11100011", 53 => "00001011", 54 => "11100110", 55 => "11110000", 
    56 => "11001110", 57 => "11110110", 58 => "00100000", 59 => "00110000", 
    60 => "00010000", 61 => "11111111", 62 => "11111111", 63 => "00010001");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

