-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity awn_forward_conv2_block_p_ZL2W2_4_15_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 7; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of awn_forward_conv2_block_p_ZL2W2_4_15_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "1010011", 1 => "0101011", 2 => "1000100", 3 => "0001001", 
    4 => "0011001", 5 => "0000111", 6 => "1111111", 7 => "0000001", 
    8 => "0011111", 9 => "0001011", 10 => "0100110", 11 => "0010010", 
    12 => "0011011", 13 => "0101000", 14 => "1101001", 15 => "0001010", 
    16 => "1001010", 17 => "0000010", 18 => "1101000", 19 => "0000000", 
    20 => "0101010", 21 => "0010111", 22 => "0001110", 23 => "0000011", 
    24 => "0011010", 25 => "1111110", 26 => "1001111", 27 => "1101111", 
    28 => "1101110", 29 => "0011110", 30 => "1111011", 31 => "0010011", 
    32 => "0101000", 33 => "0101001", 34 => "1111110", 35 => "0101101", 
    36 => "0010101", 37 => "0000110", 38 => "0000001", 39 => "1100000", 
    40 => "1110100", 41 => "0001100", 42 => "1100001", 43 => "1111101", 
    44 => "0111011", 45 => "0110000", 46 => "1011010", 47 => "1110101", 
    48 => "0001000", 49 => "0010000", 50 => "0010011", 51 => "1110101", 
    52 => "0000011", 53 => "0111110", 54 => "0100110", 55 => "1100111", 
    56 => "1111000", 57 => "0011001", 58 => "0010100", 59 => "1111111", 
    60 => "0001000", 61 => "1100011", 62 => "1110000", 63 => "0100100");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

