// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module awn_forward_linear_acc_128_32_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        x_address0,
        x_ce0,
        x_q0,
        x_address1,
        x_ce1,
        x_q1,
        out_r_address0,
        out_r_ce0,
        out_r_we0,
        out_r_d0
);

parameter    ap_ST_fsm_state1 = 18'd1;
parameter    ap_ST_fsm_state2 = 18'd2;
parameter    ap_ST_fsm_state3 = 18'd4;
parameter    ap_ST_fsm_state4 = 18'd8;
parameter    ap_ST_fsm_state5 = 18'd16;
parameter    ap_ST_fsm_state6 = 18'd32;
parameter    ap_ST_fsm_state7 = 18'd64;
parameter    ap_ST_fsm_state8 = 18'd128;
parameter    ap_ST_fsm_state9 = 18'd256;
parameter    ap_ST_fsm_state10 = 18'd512;
parameter    ap_ST_fsm_state11 = 18'd1024;
parameter    ap_ST_fsm_state12 = 18'd2048;
parameter    ap_ST_fsm_state13 = 18'd4096;
parameter    ap_ST_fsm_state14 = 18'd8192;
parameter    ap_ST_fsm_state15 = 18'd16384;
parameter    ap_ST_fsm_state16 = 18'd32768;
parameter    ap_ST_fsm_state17 = 18'd65536;
parameter    ap_ST_fsm_state18 = 18'd131072;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [4:0] x_address0;
output   x_ce0;
input  [6:0] x_q0;
output  [4:0] x_address1;
output   x_ce1;
input  [6:0] x_q1;
output  [6:0] out_r_address0;
output   out_r_ce0;
output   out_r_we0;
output  [19:0] out_r_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[4:0] x_address0;
reg x_ce0;
reg[4:0] x_address1;
reg x_ce1;

(* fsm_encoding = "none" *) reg   [17:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [6:0] x_load_reg_545;
wire    ap_CS_fsm_state2;
reg   [6:0] x_load_255_reg_550;
reg   [6:0] x_load_256_reg_565;
wire    ap_CS_fsm_state3;
reg   [6:0] x_load_257_reg_570;
reg   [6:0] x_load_258_reg_585;
wire    ap_CS_fsm_state4;
reg   [6:0] x_load_259_reg_590;
reg   [6:0] x_load_260_reg_605;
wire    ap_CS_fsm_state5;
reg   [6:0] x_load_261_reg_610;
reg   [6:0] x_load_262_reg_625;
wire    ap_CS_fsm_state6;
reg   [6:0] x_load_263_reg_630;
reg   [6:0] x_load_264_reg_645;
wire    ap_CS_fsm_state7;
reg   [6:0] x_load_265_reg_650;
reg   [6:0] x_load_266_reg_665;
wire    ap_CS_fsm_state8;
reg   [6:0] x_load_267_reg_670;
reg   [6:0] x_load_268_reg_685;
wire    ap_CS_fsm_state9;
reg   [6:0] x_load_269_reg_690;
reg   [6:0] x_load_270_reg_705;
wire    ap_CS_fsm_state10;
reg   [6:0] x_load_271_reg_710;
reg   [6:0] x_load_272_reg_725;
wire    ap_CS_fsm_state11;
reg   [6:0] x_load_273_reg_730;
reg   [6:0] x_load_274_reg_745;
wire    ap_CS_fsm_state12;
reg   [6:0] x_load_275_reg_750;
reg   [6:0] x_load_276_reg_765;
wire    ap_CS_fsm_state13;
reg   [6:0] x_load_277_reg_770;
reg   [6:0] x_load_278_reg_785;
wire    ap_CS_fsm_state14;
reg   [6:0] x_load_279_reg_790;
reg   [6:0] x_load_280_reg_805;
wire    ap_CS_fsm_state15;
reg   [6:0] x_load_281_reg_810;
reg   [6:0] x_load_282_reg_825;
wire    ap_CS_fsm_state16;
reg   [6:0] x_load_283_reg_830;
reg   [6:0] x_load_284_reg_845;
wire    ap_CS_fsm_state17;
reg   [6:0] x_load_285_reg_850;
wire    grp_linear_acc_128_32_Pipeline_VITIS_LOOP_186_1_fu_431_ap_start;
wire    grp_linear_acc_128_32_Pipeline_VITIS_LOOP_186_1_fu_431_ap_done;
wire    grp_linear_acc_128_32_Pipeline_VITIS_LOOP_186_1_fu_431_ap_idle;
wire    grp_linear_acc_128_32_Pipeline_VITIS_LOOP_186_1_fu_431_ap_ready;
wire   [6:0] grp_linear_acc_128_32_Pipeline_VITIS_LOOP_186_1_fu_431_out_r_address0;
wire    grp_linear_acc_128_32_Pipeline_VITIS_LOOP_186_1_fu_431_out_r_ce0;
wire    grp_linear_acc_128_32_Pipeline_VITIS_LOOP_186_1_fu_431_out_r_we0;
wire   [19:0] grp_linear_acc_128_32_Pipeline_VITIS_LOOP_186_1_fu_431_out_r_d0;
reg    grp_linear_acc_128_32_Pipeline_VITIS_LOOP_186_1_fu_431_ap_start_reg;
wire    ap_CS_fsm_state18;
reg   [17:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
reg    ap_ST_fsm_state18_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 18'd1;
#0 grp_linear_acc_128_32_Pipeline_VITIS_LOOP_186_1_fu_431_ap_start_reg = 1'b0;
end

awn_forward_linear_acc_128_32_Pipeline_VITIS_LOOP_186_1 grp_linear_acc_128_32_Pipeline_VITIS_LOOP_186_1_fu_431(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_linear_acc_128_32_Pipeline_VITIS_LOOP_186_1_fu_431_ap_start),
    .ap_done(grp_linear_acc_128_32_Pipeline_VITIS_LOOP_186_1_fu_431_ap_done),
    .ap_idle(grp_linear_acc_128_32_Pipeline_VITIS_LOOP_186_1_fu_431_ap_idle),
    .ap_ready(grp_linear_acc_128_32_Pipeline_VITIS_LOOP_186_1_fu_431_ap_ready),
    .zext_ln186(x_load_285_reg_850),
    .conv12_15_cast(x_load_269_reg_690),
    .conv12_30_cast(x_load_284_reg_845),
    .conv12_17_cast(x_load_271_reg_710),
    .conv12_9_cast(x_load_263_reg_630),
    .conv12_29_cast(x_load_283_reg_830),
    .conv12_24_cast(x_load_278_reg_785),
    .conv12_14_cast(x_load_268_reg_685),
    .conv12_cast(x_load_reg_545),
    .conv12_28_cast(x_load_282_reg_825),
    .conv12_18_cast(x_load_272_reg_725),
    .conv12_6_cast(x_load_260_reg_605),
    .conv12_13_cast(x_load_267_reg_670),
    .conv12_21_cast(x_load_275_reg_750),
    .conv12_27_cast(x_load_281_reg_810),
    .conv12_4_cast(x_load_258_reg_585),
    .conv12_10_cast(x_load_264_reg_645),
    .conv12_23_cast(x_load_277_reg_770),
    .conv12_3_cast(x_load_257_reg_570),
    .conv12_19_cast(x_load_273_reg_730),
    .conv12_26_cast(x_load_280_reg_805),
    .conv12_12_cast(x_load_266_reg_665),
    .conv12_5_cast(x_load_259_reg_590),
    .conv12_1_cast(x_load_255_reg_550),
    .conv12_2_cast(x_load_256_reg_565),
    .conv12_8_cast(x_load_262_reg_625),
    .conv12_11_cast(x_load_265_reg_650),
    .conv12_25_cast(x_load_279_reg_790),
    .conv12_7_cast(x_load_261_reg_610),
    .conv12_22_cast(x_load_276_reg_765),
    .conv12_20_cast(x_load_274_reg_745),
    .conv12_16_cast(x_load_270_reg_705),
    .out_r_address0(grp_linear_acc_128_32_Pipeline_VITIS_LOOP_186_1_fu_431_out_r_address0),
    .out_r_ce0(grp_linear_acc_128_32_Pipeline_VITIS_LOOP_186_1_fu_431_out_r_ce0),
    .out_r_we0(grp_linear_acc_128_32_Pipeline_VITIS_LOOP_186_1_fu_431_out_r_we0),
    .out_r_d0(grp_linear_acc_128_32_Pipeline_VITIS_LOOP_186_1_fu_431_out_r_d0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_linear_acc_128_32_Pipeline_VITIS_LOOP_186_1_fu_431_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state17)) begin
            grp_linear_acc_128_32_Pipeline_VITIS_LOOP_186_1_fu_431_ap_start_reg <= 1'b1;
        end else if ((grp_linear_acc_128_32_Pipeline_VITIS_LOOP_186_1_fu_431_ap_ready == 1'b1)) begin
            grp_linear_acc_128_32_Pipeline_VITIS_LOOP_186_1_fu_431_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        x_load_255_reg_550 <= x_q0;
        x_load_reg_545 <= x_q1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        x_load_256_reg_565 <= x_q1;
        x_load_257_reg_570 <= x_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        x_load_258_reg_585 <= x_q1;
        x_load_259_reg_590 <= x_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        x_load_260_reg_605 <= x_q1;
        x_load_261_reg_610 <= x_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        x_load_262_reg_625 <= x_q1;
        x_load_263_reg_630 <= x_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        x_load_264_reg_645 <= x_q1;
        x_load_265_reg_650 <= x_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        x_load_266_reg_665 <= x_q1;
        x_load_267_reg_670 <= x_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        x_load_268_reg_685 <= x_q1;
        x_load_269_reg_690 <= x_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        x_load_270_reg_705 <= x_q1;
        x_load_271_reg_710 <= x_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        x_load_272_reg_725 <= x_q1;
        x_load_273_reg_730 <= x_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        x_load_274_reg_745 <= x_q1;
        x_load_275_reg_750 <= x_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        x_load_276_reg_765 <= x_q1;
        x_load_277_reg_770 <= x_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        x_load_278_reg_785 <= x_q1;
        x_load_279_reg_790 <= x_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        x_load_280_reg_805 <= x_q1;
        x_load_281_reg_810 <= x_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        x_load_282_reg_825 <= x_q1;
        x_load_283_reg_830 <= x_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        x_load_284_reg_845 <= x_q1;
        x_load_285_reg_850 <= x_q0;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

always @ (*) begin
    if ((grp_linear_acc_128_32_Pipeline_VITIS_LOOP_186_1_fu_431_ap_done == 1'b0)) begin
        ap_ST_fsm_state18_blk = 1'b1;
    end else begin
        ap_ST_fsm_state18_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((((grp_linear_acc_128_32_Pipeline_VITIS_LOOP_186_1_fu_431_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state18)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_linear_acc_128_32_Pipeline_VITIS_LOOP_186_1_fu_431_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state18))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        x_address0 = 64'd31;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        x_address0 = 64'd29;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        x_address0 = 64'd27;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        x_address0 = 64'd25;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        x_address0 = 64'd23;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        x_address0 = 64'd21;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        x_address0 = 64'd19;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        x_address0 = 64'd17;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        x_address0 = 64'd15;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        x_address0 = 64'd13;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        x_address0 = 64'd11;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        x_address0 = 64'd9;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        x_address0 = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        x_address0 = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        x_address0 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        x_address0 = 64'd1;
    end else begin
        x_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        x_address1 = 64'd30;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        x_address1 = 64'd28;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        x_address1 = 64'd26;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        x_address1 = 64'd24;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        x_address1 = 64'd22;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        x_address1 = 64'd20;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        x_address1 = 64'd18;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        x_address1 = 64'd16;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        x_address1 = 64'd14;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        x_address1 = 64'd12;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        x_address1 = 64'd10;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        x_address1 = 64'd8;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        x_address1 = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        x_address1 = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        x_address1 = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        x_address1 = 64'd0;
    end else begin
        x_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        x_ce0 = 1'b1;
    end else begin
        x_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        x_ce1 = 1'b1;
    end else begin
        x_ce1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            if (((grp_linear_acc_128_32_Pipeline_VITIS_LOOP_186_1_fu_431_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state18))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign grp_linear_acc_128_32_Pipeline_VITIS_LOOP_186_1_fu_431_ap_start = grp_linear_acc_128_32_Pipeline_VITIS_LOOP_186_1_fu_431_ap_start_reg;

assign out_r_address0 = grp_linear_acc_128_32_Pipeline_VITIS_LOOP_186_1_fu_431_out_r_address0;

assign out_r_ce0 = grp_linear_acc_128_32_Pipeline_VITIS_LOOP_186_1_fu_431_out_r_ce0;

assign out_r_d0 = grp_linear_acc_128_32_Pipeline_VITIS_LOOP_186_1_fu_431_out_r_d0;

assign out_r_we0 = grp_linear_acc_128_32_Pipeline_VITIS_LOOP_186_1_fu_431_out_r_we0;

endmodule //awn_forward_linear_acc_128_32_s
