-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity awn_forward_conv2_block_p_ZL2W2_1_42_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 7; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of awn_forward_conv2_block_p_ZL2W2_1_42_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "1101000", 1 => "0001110", 2 => "1110001", 3 => "0001101", 
    4 => "1111100", 5 => "0011000", 6 => "1111100", 7 => "0010110", 
    8 => "1110101", 9 => "0001110", 10 => "0101011", 11 => "0101100", 
    12 => "0001010", 13 => "0011011", 14 => "1111100", 15 => "0000100", 
    16 => "1110101", 17 => "0100001", 18 => "1110101", 19 => "0001000", 
    20 => "1110100", 21 => "0010101", 22 => "1111110", 23 => "0010100", 
    24 => "0000010", 25 => "1111100", 26 => "0100100", 27 => "0001100", 
    28 => "0010000", 29 => "1111000", 30 => "1100100", 31 => "1111000", 
    32 => "0000000", 33 => "0001000", 34 => "0100011", 35 => "1101100", 
    36 => "1101001", 37 => "1110111", 38 => "0011001", 39 => "1011010", 
    40 => "1111010", 41 => "1111100", 42 => "0000000", 43 => "0000011", 
    44 => "0001001", 45 => "1110000", 46 => "0011000", 47 => "0011001", 
    48 => "0010111", 49 => "0011101", 50 => "0001011", 51 => "1101010", 
    52 => "1110101", 53 => "1110010", 54 => "0000101", 55 => "0001000", 
    56 => "1100110", 57 => "1111001", 58 => "0011101", 59 => "0001110", 
    60 => "1110100", 61 => "0001110", 62 => "0011101", 63 => "0010100");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

