-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity awn_forward_conv2_block_p_ZL2W2_4_40_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of awn_forward_conv2_block_p_ZL2W2_4_40_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "11110101", 1 => "11111101", 2 => "00000111", 3 => "00001011", 
    4 => "11111000", 5 => "11110001", 6 => "11101110", 7 => "11101011", 
    8 => "11011011", 9 => "11101100", 10 => "00100001", 11 => "11101011", 
    12 => "00000100", 13 => "00010011", 14 => "11101100", 15 => "11101110", 
    16 => "11000110", 17 => "00010111", 18 => "00011100", 19 => "11110101", 
    20 => "11111100", 21 => "11010100", 22 => "00000011", 23 => "11010111", 
    24 => "00011100", 25 => "11111001", 26 => "11110000", 27 => "00100001", 
    28 => "11011011", 29 => "11100000", 30 => "11110001", 31 => "11110000", 
    32 => "11111001", 33 => "11110001", 34 => "00000011", 35 => "01000111", 
    36 => "00001100", 37 => "00000110", 38 => "11100101", 39 => "00000000", 
    40 => "11000111", 41 => "00000100", 42 => "11111110", 43 => "00100000", 
    44 => "01000100", 45 => "00100111", 46 => "11110111", 47 => "11111011", 
    48 => "11011000", 49 => "00001001", 50 => "00001100", 51 => "11111110", 
    52 => "00010001", 53 => "11110101", 54 => "01110101", 55 => "11101111", 
    56 => "00010111", 57 => "11111110", 58 => "11011101", 59 => "00001000", 
    60 => "00001110", 61 => "00000101", 62 => "11111000", 63 => "00000101");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

