-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity awn_forward_conv2_block_p_ZL2W2_0_49_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 7; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of awn_forward_conv2_block_p_ZL2W2_0_49_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "0110001", 1 => "1111010", 2 => "1110011", 3 => "0000000", 
    4 => "1101011", 5 => "0010110", 6 => "0001100", 7 => "0100101", 
    8 => "1101011", 9 => "1101000", 10 => "1011010", 11 => "1010000", 
    12 => "1111110", 13 => "1111011", 14 => "0011001", 15 => "1111011", 
    16 => "0010100", 17 => "1100011", 18 => "0010000", 19 => "1111001", 
    20 => "1011011", 21 => "1101101", 22 => "1101110", 23 => "1111111", 
    24 => "1110111", 25 => "0000010", 26 => "0000010", 27 => "0001111", 
    28 => "1110101", 29 => "1101000", 30 => "1101011", 31 => "0011101", 
    32 => "0000111", 33 => "1100110", 34 => "0000011", 35 => "0000101", 
    36 => "0010010", 37 => "1011010", 38 => "1100111", 39 => "0010100", 
    40 => "1101111", 41 => "0001111", 42 => "1111100", 43 => "0010001", 
    44 => "1111110", 45 => "0001100", 46 => "1111111", 47 => "0001101", 
    48 => "0010101", 49 => "0000110", 50 => "1101111", 51 => "0010100", 
    52 => "0001100", 53 => "1011100", 54 => "0010100", 55 => "0010001", 
    56 => "0100000", 57 => "1111101", 58 => "1111001", 59 => "1110000", 
    60 => "1110101", 61 => "0011000", 62 => "0001110", 63 => "0010011");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

