-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity awn_forward_conv2_block_p_ZL2W2_3_7_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 7; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of awn_forward_conv2_block_p_ZL2W2_3_7_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "0000000", 1 => "1111011", 2 => "0000111", 3 => "1110011", 
    4 => "0000000", 5 => "0000111", 6 => "0001101", 7 => "0000000", 
    8 => "1110010", 9 => "0001001", 10 => "1110110", 11 => "0000111", 
    12 => "0000001", 13 => "0000001", 14 => "1111101", 15 => "0000111", 
    16 => "1101101", 17 => "1101010", 18 => "1111000", 19 => "1110001", 
    20 => "1111001", 21 => "1111010", 22 => "1110001", 23 => "1100100", 
    24 => "1010111", 25 => "0001101", 26 => "0010101", 27 => "1101101", 
    28 => "1111101", 29 => "0000000", 30 => "0001111", 31 => "0101101", 
    32 => "0000101", 33 => "1101111", 34 => "1110110", 35 => "0000000", 
    36 => "1110000", 37 => "1001110", 38 => "1111011", 39 => "1000100", 
    40 => "1110001", 41 => "1101110", 42 => "1111001", 43 => "0000001", 
    44 => "1101001", 45 => "0101110", 46 => "1111100", 47 => "0000110", 
    48 => "0101111", 49 => "0011001", 50 => "0000110", 51 => "1111111", 
    52 => "0010100", 53 => "1100010", 54 => "0000001", 55 => "0011111", 
    56 => "1111010", 57 => "1100011", 58 => "0001101", 59 => "0110100", 
    60 => "0001010", 61 => "0001011", 62 => "0000010", 63 => "0100010");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

