-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity awn_forward_conv2_block_p_ZL2W2_0_55_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 7; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of awn_forward_conv2_block_p_ZL2W2_0_55_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "1101001", 1 => "0000100", 2 => "1100111", 3 => "1111011", 
    4 => "0000010", 5 => "0001001", 6 => "0000101", 7 => "1101101", 
    8 => "1110111", 9 => "1110100", 10 => "0000110", 11 => "0000000", 
    12 => "0000110", 13 => "0001110", 14 => "1110011", 15 => "0010000", 
    16 => "1010010", 17 => "1100000", 18 => "1110111", 19 => "1111100", 
    20 => "1111011", 21 => "1101110", 22 => "1111011", 23 => "1100010", 
    24 => "1000010", 25 => "0001111", 26 => "0001101", 27 => "1111111", 
    28 => "0001110", 29 => "1110111", 30 => "0001010", 31 => "0010100", 
    32 => "1100100", 33 => "0000100", 34 => "0000011", 35 => "1111110", 
    36 => "1110000", 37 => "1011011", 38 => "1001000", 39 => "1101100", 
    40 => "1100010", 41 => "1101110", 42 => "0000110", 43 => "1110010", 
    44 => "1101101", 45 => "0111010", 46 => "0010011", 47 => "0000010", 
    48 => "0001110", 49 => "0000010", 50 => "1111110", 51 => "1111000", 
    52 => "0001101", 53 => "0000110", 54 => "1001110", 55 => "0100011", 
    56 => "0001000", 57 => "1110111", 58 => "1110010", 59 => "0100010", 
    60 => "0000100", 61 => "0001100", 62 => "0001001", 63 => "0001111");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

