-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity awn_forward_conv2_block_p_ZL2W2_3_22_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 7; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of awn_forward_conv2_block_p_ZL2W2_3_22_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "1011101", 1 => "1111101", 2 => "0010001", 3 => "1110100", 
    4 => "0000110", 5 => "1111100", 6 => "1111010", 7 => "0101110", 
    8 => "1111001", 9 => "0001100", 10 => "0100001", 11 => "0000000", 
    12 => "1110111", 13 => "0001101", 14 => "1101110", 15 => "0010101", 
    16 => "1111101", 17 => "0000000", 18 => "1111101", 19 => "1110010", 
    20 => "1011111", 21 => "1101001", 22 => "1101111", 23 => "1111010", 
    24 => "0001111", 25 => "1101101", 26 => "0001001", 27 => "1111000", 
    28 => "1010100", 29 => "0001100", 30 => "0001001", 31 => "1111000", 
    32 => "0110000", 33 => "1111011", 34 => "1011101", 35 => "1110011", 
    36 => "0010011", 37 => "1110000", 38 => "1110110", 39 => "1111101", 
    40 => "0001010", 41 => "0001101", 42 => "1110101", 43 => "1110111", 
    44 => "0100111", 45 => "1111001", 46 => "1110111", 47 => "0000000", 
    48 => "0010010", 49 => "0100100", 50 => "0100001", 51 => "1100011", 
    52 => "1110100", 53 => "1101101", 54 => "0000111", 55 => "0001000", 
    56 => "0010110", 57 => "0011101", 58 => "1101110", 59 => "1110110", 
    60 => "1100010", 61 => "1111110", 62 => "1110101", 63 => "0001010");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

