-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity awn_forward_conv2_block_p_ZL2W2_0_52_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of awn_forward_conv2_block_p_ZL2W2_0_52_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00001010", 1 => "11100100", 2 => "11011101", 3 => "11101110", 
    4 => "11110101", 5 => "00000011", 6 => "00001110", 7 => "00001110", 
    8 => "11101001", 9 => "11101111", 10 => "11101111", 11 => "00000010", 
    12 => "11110001", 13 => "11100100", 14 => "00010101", 15 => "00001001", 
    16 => "11100111", 17 => "11010100", 18 => "00000010", 19 => "00010000", 
    20 => "11101101", 21 => "11110011", 22 => "11111111", 23 => "00001000", 
    24 => "10011010", 25 => "00001000", 26 => "00011000", 27 => "00000000", 
    28 => "11101001", 29 => "11101110", 30 => "11110111", 31 => "00000000", 
    32 => "00010010", 33 => "11101110", 34 => "11111010", 35 => "11010101", 
    36 => "00010011", 37 => "11111100", 38 => "11111101", 39 => "00000100", 
    40 => "00000010", 41 => "00001110", 42 => "11111101", 43 => "11111011", 
    44 => "11000000", 45 => "00111001", 46 => "11100100", 47 => "11111100", 
    48 => "00001000", 49 => "00001010", 50 => "11100110", 51 => "11111110", 
    52 => "00001100", 53 => "11111011", 54 => "11110001", 55 => "00000111", 
    56 => "00001110", 57 => "00010010", 58 => "11111010", 59 => "00010001", 
    60 => "00001010", 61 => "00000100", 62 => "11111101", 63 => "00010101");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

