-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity awn_forward_conv2_block_p_ZL2W2_3_27_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of awn_forward_conv2_block_p_ZL2W2_3_27_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "11110110", 1 => "00000000", 2 => "00000101", 3 => "00000111", 
    4 => "00010000", 5 => "11101100", 6 => "00011001", 7 => "00001111", 
    8 => "00000110", 9 => "00001011", 10 => "00011000", 11 => "10111011", 
    12 => "00000000", 13 => "11111001", 14 => "11111101", 15 => "00100000", 
    16 => "00100000", 17 => "00011011", 18 => "00001000", 19 => "00000111", 
    20 => "11110110", 21 => "00001000", 22 => "00000110", 23 => "11110100", 
    24 => "11111011", 25 => "11100101", 26 => "11001110", 27 => "00010000", 
    28 => "00000010", 29 => "11111011", 30 => "11110011", 31 => "00100011", 
    32 => "00000000", 33 => "11111111", 34 => "11101011", 35 => "11101101", 
    36 => "00001101", 37 => "11010011", 38 => "11101000", 39 => "11001110", 
    40 => "00000000", 41 => "00000100", 42 => "00000001", 43 => "11111010", 
    44 => "00010010", 45 => "11111100", 46 => "00001001", 47 => "00011100", 
    48 => "00111100", 49 => "00010111", 50 => "00001100", 51 => "00001000", 
    52 => "10110100", 53 => "00001000", 54 => "11111100", 55 => "00011000", 
    56 => "00001101", 57 => "00010000", 58 => "11011101", 59 => "11010101", 
    60 => "11011011", 61 => "00001010", 62 => "11110100", 63 => "00110001");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

