-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity awn_forward_conv2_block_p_ZL2W2_2_5_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 7; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of awn_forward_conv2_block_p_ZL2W2_2_5_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "0000101", 1 => "1101110", 2 => "0001011", 3 => "1101110", 
    4 => "1111110", 5 => "0000100", 6 => "1110001", 7 => "0011100", 
    8 => "0010100", 9 => "1111111", 10 => "0000010", 11 => "0000100", 
    12 => "0000101", 13 => "1101000", 14 => "0000101", 15 => "1101010", 
    16 => "0001010", 17 => "1100010", 18 => "0001000", 19 => "0001011", 
    20 => "0001100", 21 => "0001011", 22 => "0000000", 23 => "0001000", 
    24 => "1111101", 25 => "1111011", 26 => "1101001", 27 => "1010111", 
    28 => "0100100", 29 => "0100000", 30 => "1011110", 31 => "1010000", 
    32 => "0001010", 33 => "0011110", 34 => "1101001", 35 => "1111111", 
    36 => "1101011", 37 => "1111001", 38 => "0011000", 39 => "0011100", 
    40 => "0011000", 41 => "1111001", 42 => "0010001", 43 => "0001110", 
    44 => "1101101", 45 => "1010100", 46 => "0000100", 47 => "1110101", 
    48 => "1101101", 49 => "0100001", 50 => "1101110", 51 => "1111101", 
    52 => "0001101", 53 => "0101110", 54 => "1111111", 55 => "0010111", 
    56 => "1100001", 57 => "0010100", 58 => "1100010", 59 => "0100001", 
    60 => "1111110", 61 => "1110000", 62 => "0001010", 63 => "0011000");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

