-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity awn_forward_conv2_block_p_ZL2W2_0_39_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 7; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of awn_forward_conv2_block_p_ZL2W2_0_39_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "0000001", 1 => "0010001", 2 => "0010101", 3 => "1111110", 
    4 => "0001011", 5 => "1111110", 6 => "1001010", 7 => "0001000", 
    8 => "1110101", 9 => "0010011", 10 => "1111000", 11 => "0010011", 
    12 => "0100010", 13 => "0011000", 14 => "1110011", 15 => "0000001", 
    16 => "0010101", 17 => "0011001", 18 => "0000110", 19 => "0000101", 
    20 => "1100011", 21 => "1111011", 22 => "1111000", 23 => "0001110", 
    24 => "1110100", 25 => "0000100", 26 => "0010011", 27 => "1100010", 
    28 => "0001011", 29 => "0000110", 30 => "0001010", 31 => "1001011", 
    32 => "0010111", 33 => "1101000", 34 => "0010110", 35 => "1101011", 
    36 => "0001100", 37 => "0100101", 38 => "0101001", 39 => "1100000", 
    40 => "0001001", 41 => "0010101", 42 => "0001100", 43 => "1101101", 
    44 => "1111001", 45 => "1111000", 46 => "1110011", 47 => "0001100", 
    48 => "1011011", 49 => "0010101", 50 => "0011111", 51 => "1101110", 
    52 => "1111010", 53 => "1111111", 54 => "0011000", 55 => "1110111", 
    56 => "1110011", 57 => "1001101", 58 => "0100000", 59 => "0000000", 
    60 => "0000001", 61 => "0000111", 62 => "0000110", 63 => "1010101");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

