-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity awn_forward_conv2_block_p_ZL2W2_1_13_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 7; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of awn_forward_conv2_block_p_ZL2W2_1_13_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "0000100", 1 => "0001100", 2 => "1111011", 3 => "0100010", 
    4 => "1101110", 5 => "0010000", 6 => "1111101", 7 => "1110001", 
    8 => "0000011", 9 => "0000000", 10 => "0100111", 11 => "0010010", 
    12 => "0001000", 13 => "0001001", 14 => "0000010", 15 => "1111001", 
    16 => "1101011", 17 => "1101000", 18 => "1101101", 19 => "1111011", 
    20 => "0000010", 21 => "0001000", 22 => "1001010", 23 => "0100011", 
    24 => "1011111", 25 => "1110000", 26 => "0000101", 27 => "0011111", 
    28 => "0000101", 29 => "1111001", 30 => "0000110", 31 => "0001100", 
    32 => "0101001", 33 => "1111101", 34 => "1100010", 35 => "0011100", 
    36 => "0000001", 37 => "1011001", 38 => "1100000", 39 => "0000101", 
    40 => "1111001", 41 => "1100001", 42 => "0001000", 43 => "1011011", 
    44 => "1100101", 45 => "0100011", 46 => "0000110", 47 => "1111100", 
    48 => "1101111", 49 => "0010101", 50 => "0001010", 51 => "1000101", 
    52 => "0000110", 53 => "0010111", 54 => "0001000", 55 => "0001111", 
    56 => "1000111", 57 => "0001010", 58 => "0010111", 59 => "1101110", 
    60 => "0001110", 61 => "1110111", 62 => "0001111", 63 => "0001101");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

