-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity awn_forward_conv2_block_p_ZL2W2_0_47_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of awn_forward_conv2_block_p_ZL2W2_0_47_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "11011011", 1 => "11111100", 2 => "01001110", 3 => "00001010", 
    4 => "00011010", 5 => "10111101", 6 => "00010111", 7 => "11111010", 
    8 => "00001100", 9 => "00000111", 10 => "00110000", 11 => "00010001", 
    12 => "11111010", 13 => "00010001", 14 => "11110100", 15 => "11111100", 
    16 => "11100111", 17 => "11110001", 18 => "11110101", 19 => "00000101", 
    20 => "00000110", 21 => "00011000", 22 => "00111101", 23 => "00000011", 
    24 => "00001111", 25 => "11111111", 26 => "11101001", 27 => "11110110", 
    28 => "00001001", 29 => "11111000", 30 => "00001011", 31 => "11101100", 
    32 => "11110011", 33 => "00100100", 34 => "00101000", 35 => "11110101", 
    36 => "11111101", 37 => "11010001", 38 => "00000100", 39 => "01001010", 
    40 => "00010100", 41 => "00000011", 42 => "11111111", 43 => "10111100", 
    44 => "00100001", 45 => "11000110", 46 => "11101011", 47 => "00001001", 
    48 => "11111100", 49 => "00110110", 50 => "00000111", 51 => "11101101", 
    52 => "00011111", 53 => "00101000", 54 => "11100010", 55 => "11111000", 
    56 => "11111111", 57 => "00001101", 58 => "11111011", 59 => "11111011", 
    60 => "11101110", 61 => "11110011", 62 => "11100101", 63 => "00001100");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

