-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity awn_forward_conv2_block_p_ZL2W2_3_52_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 7; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of awn_forward_conv2_block_p_ZL2W2_3_52_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "1110110", 1 => "1101111", 2 => "1110111", 3 => "1110000", 
    4 => "1111111", 5 => "0000100", 6 => "0000101", 7 => "1011001", 
    8 => "0000110", 9 => "0000101", 10 => "1111111", 11 => "0010100", 
    12 => "1110110", 13 => "1110100", 14 => "0000100", 15 => "0011101", 
    16 => "1011110", 17 => "1110100", 18 => "1110110", 19 => "0010100", 
    20 => "0001000", 21 => "0001000", 22 => "1111011", 23 => "0010101", 
    24 => "1100000", 25 => "0001010", 26 => "0000001", 27 => "1110101", 
    28 => "1110111", 29 => "0001011", 30 => "0011101", 31 => "0100001", 
    32 => "1110011", 33 => "0000101", 34 => "1111010", 35 => "1101111", 
    36 => "0000011", 37 => "1101110", 38 => "1111100", 39 => "1000000", 
    40 => "0001100", 41 => "1111011", 42 => "0000110", 43 => "0000110", 
    44 => "1110111", 45 => "0001110", 46 => "0000000", 47 => "1111010", 
    48 => "0100011", 49 => "1111010", 50 => "1110000", 51 => "1111000", 
    52 => "0011011", 53 => "1111110", 54 => "1101101", 55 => "0010010", 
    56 => "1110010", 57 => "1111111", 58 => "1110110", 59 => "0100110", 
    60 => "0000011", 61 => "0000110", 62 => "0000110", 63 => "0001100");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

