-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity awn_forward_conv2_block_p_ZL2W2_3_15_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 7; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of awn_forward_conv2_block_p_ZL2W2_3_15_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "1101101", 1 => "0000111", 2 => "1011100", 3 => "0010100", 
    4 => "0000110", 5 => "1111101", 6 => "1110001", 7 => "0110100", 
    8 => "0001000", 9 => "0000101", 10 => "0110000", 11 => "1111000", 
    12 => "1101111", 13 => "0000111", 14 => "1011010", 15 => "0000011", 
    16 => "1111000", 17 => "1110110", 18 => "1100110", 19 => "1101100", 
    20 => "0010001", 21 => "1111000", 22 => "0010010", 23 => "1100000", 
    24 => "0101010", 25 => "1110111", 26 => "0000011", 27 => "1101101", 
    28 => "1100111", 29 => "0001000", 30 => "0001101", 31 => "0001101", 
    32 => "0101010", 33 => "0101001", 34 => "1101010", 35 => "0010101", 
    36 => "0001000", 37 => "1010110", 38 => "1011010", 39 => "0001101", 
    40 => "1100101", 41 => "0010001", 42 => "1010111", 43 => "0100111", 
    44 => "0100000", 45 => "0100010", 46 => "1110111", 47 => "1110101", 
    48 => "0011001", 49 => "0010001", 50 => "0000001", 51 => "1101111", 
    52 => "1011110", 53 => "0000010", 54 => "0100100", 55 => "0001000", 
    56 => "0001001", 57 => "0011001", 58 => "1011001", 59 => "0000011", 
    60 => "1111101", 61 => "1111001", 62 => "1100111", 63 => "1110111");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

