-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity awn_forward_conv2_block_p_ZL2W2_4_29_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of awn_forward_conv2_block_p_ZL2W2_4_29_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111001", 1 => "11111001", 2 => "11100100", 3 => "11101110", 
    4 => "11110010", 5 => "11110011", 6 => "11110111", 7 => "11100101", 
    8 => "00001101", 9 => "11110000", 10 => "11110100", 11 => "11111100", 
    12 => "00010100", 13 => "00000101", 14 => "00011011", 15 => "00101010", 
    16 => "11010000", 17 => "00001010", 18 => "00100110", 19 => "00010100", 
    20 => "00011000", 21 => "00011110", 22 => "00000001", 23 => "00001010", 
    24 => "00011000", 25 => "00011011", 26 => "00001011", 27 => "11010011", 
    28 => "00111101", 29 => "11110110", 30 => "11101110", 31 => "11111011", 
    32 => "11001001", 33 => "00100110", 34 => "11010001", 35 => "00000010", 
    36 => "11011001", 37 => "00000100", 38 => "00010001", 39 => "00011001", 
    40 => "00001101", 41 => "11100101", 42 => "00001101", 43 => "11100011", 
    44 => "11001110", 45 => "01001110", 46 => "00101111", 47 => "00000011", 
    48 => "00001111", 49 => "00100011", 50 => "00000101", 51 => "00101101", 
    52 => "11100011", 53 => "00001111", 54 => "11101100", 55 => "00000110", 
    56 => "00010101", 57 => "11101100", 58 => "11101101", 59 => "11101000", 
    60 => "00001011", 61 => "00010001", 62 => "00010001", 63 => "00011100");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

