-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity awn_forward_conv2_block_p_ZL2W2_0_23_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of awn_forward_conv2_block_p_ZL2W2_0_23_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00001110", 1 => "11110011", 2 => "00011000", 3 => "11111010", 
    4 => "11111101", 5 => "00000000", 6 => "00001101", 7 => "00011011", 
    8 => "00000101", 9 => "00001000", 10 => "01001101", 11 => "11100010", 
    12 => "11101011", 13 => "11101100", 14 => "11111100", 15 => "00001110", 
    16 => "00011101", 17 => "11100101", 18 => "11111011", 19 => "00000001", 
    20 => "00010010", 21 => "11110101", 22 => "11101101", 23 => "11111001", 
    24 => "00000001", 25 => "00010100", 26 => "11100111", 27 => "00011000", 
    28 => "00000001", 29 => "00000111", 30 => "00000110", 31 => "00010000", 
    32 => "00001110", 33 => "11111110", 34 => "00011010", 35 => "00010010", 
    36 => "11111110", 37 => "00000010", 38 => "11110000", 39 => "11110111", 
    40 => "11110010", 41 => "11110001", 42 => "00001001", 43 => "00001101", 
    44 => "00000100", 45 => "11011011", 46 => "00001100", 47 => "00001010", 
    48 => "00011001", 49 => "00001001", 50 => "00010011", 51 => "00000110", 
    52 => "11001011", 53 => "00011111", 54 => "00001010", 55 => "11101011", 
    56 => "00101001", 57 => "00010100", 58 => "00010001", 59 => "11111010", 
    60 => "00001100", 61 => "11110101", 62 => "00000110", 63 => "00010110");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

