-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity awn_forward_conv2_block_p_ZL2W2_0_53_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 7; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of awn_forward_conv2_block_p_ZL2W2_0_53_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "1111101", 1 => "1011010", 2 => "0000000", 3 => "1010110", 
    4 => "1101011", 5 => "1011110", 6 => "0001010", 7 => "0010001", 
    8 => "1111001", 9 => "0000001", 10 => "0000001", 11 => "1110100", 
    12 => "1011000", 13 => "1001110", 14 => "0000100", 15 => "1110101", 
    16 => "0000011", 17 => "1101010", 18 => "0000010", 19 => "1101011", 
    20 => "0000101", 21 => "1111101", 22 => "0011000", 23 => "0000110", 
    24 => "1000101", 25 => "1101001", 26 => "0100001", 27 => "0001100", 
    28 => "1001101", 29 => "1110001", 30 => "0000001", 31 => "0010010", 
    32 => "0000111", 33 => "0010111", 34 => "0000000", 35 => "1101001", 
    36 => "0100000", 37 => "1101000", 38 => "0001010", 39 => "0000110", 
    40 => "0010010", 41 => "0011001", 42 => "1110101", 43 => "1100111", 
    44 => "1101011", 45 => "0011100", 46 => "1100010", 47 => "1011111", 
    48 => "0000001", 49 => "0000011", 50 => "0000011", 51 => "0001100", 
    52 => "0001011", 53 => "1111111", 54 => "0001010", 55 => "0011100", 
    56 => "0000100", 57 => "0011101", 58 => "0011011", 59 => "0010111", 
    60 => "1111100", 61 => "1111001", 62 => "1011100", 63 => "0001111");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

