-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity awn_forward_conv2_block_p_ZL2W2_2_23_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of awn_forward_conv2_block_p_ZL2W2_2_23_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "11111011", 1 => "11111010", 2 => "11111110", 3 => "11111000", 
    4 => "11101010", 5 => "11111101", 6 => "11101101", 7 => "01001010", 
    8 => "11110100", 9 => "11111000", 10 => "00100110", 11 => "00000010", 
    12 => "00001110", 13 => "11110001", 14 => "00001011", 15 => "00100101", 
    16 => "00100100", 17 => "11011100", 18 => "00000111", 19 => "00010001", 
    20 => "00011110", 21 => "00100000", 22 => "00000101", 23 => "00000000", 
    24 => "00011010", 25 => "00001100", 26 => "11110100", 27 => "00001111", 
    28 => "00001101", 29 => "11111100", 30 => "11111101", 31 => "11110100", 
    32 => "00100110", 33 => "00010000", 34 => "11101100", 35 => "00000001", 
    36 => "00011110", 37 => "11101100", 38 => "11111100", 39 => "00010111", 
    40 => "00000000", 41 => "00001010", 42 => "00000001", 43 => "11110111", 
    44 => "11010111", 45 => "00010011", 46 => "00000001", 47 => "00000101", 
    48 => "11110100", 49 => "00000110", 50 => "11110111", 51 => "00000100", 
    52 => "11101001", 53 => "11111101", 54 => "00001101", 55 => "00000101", 
    56 => "00010011", 57 => "00011001", 58 => "00111010", 59 => "00011010", 
    60 => "00001011", 61 => "11110011", 62 => "11111001", 63 => "00010111");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

