-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity awn_forward_conv2_block_p_ZL2W2_4_18_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 7; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of awn_forward_conv2_block_p_ZL2W2_4_18_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "0000101", 1 => "1111111", 2 => "1011011", 3 => "0100110", 
    4 => "1111100", 5 => "1101100", 6 => "1101110", 7 => "0100010", 
    8 => "0001100", 9 => "1111011", 10 => "1010101", 11 => "0110100", 
    12 => "1111011", 13 => "1111110", 14 => "0001111", 15 => "0000001", 
    16 => "1011010", 17 => "1011010", 18 => "0000000", 19 => "0000101", 
    20 => "0110011", 21 => "0001101", 22 => "0010101", 23 => "0001010", 
    24 => "0100010", 25 => "1111101", 26 => "1100101", 27 => "1010010", 
    28 => "1101101", 29 => "0000011", 30 => "1110000", 31 => "0010101", 
    32 => "1101111", 33 => "0011001", 34 => "1100000", 35 => "0001111", 
    36 => "1111010", 37 => "0001010", 38 => "0000011", 39 => "1101010", 
    40 => "0001110", 41 => "0001010", 42 => "0010000", 43 => "0001000", 
    44 => "1010100", 45 => "0001001", 46 => "1110011", 47 => "0000100", 
    48 => "0010010", 49 => "1110111", 50 => "1100011", 51 => "0010000", 
    52 => "0100101", 53 => "0010011", 54 => "0011000", 55 => "0000010", 
    56 => "1011011", 57 => "0010100", 58 => "1101001", 59 => "0011111", 
    60 => "1111011", 61 => "1110101", 62 => "1101100", 63 => "0110000");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

