-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity awn_forward_linear_acc_32_128_Pipeline_VITIS_LOOP_186_1_p_ZL4Wse0_58_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of awn_forward_linear_acc_32_128_Pipeline_VITIS_LOOP_186_1_p_ZL4Wse0_58_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "01000000", 1 => "01000010", 2 => "00011001", 3 => "11101001", 
    4 => "11110010", 5 => "01000100", 6 => "00010110", 7 => "00100101", 
    8 => "01000111", 9 => "00111000", 10 => "00000011", 11 => "00100010", 
    12 => "11001100", 13 => "01001100", 14 => "11110101", 15 => "00000011", 
    16 => "00010010", 17 => "11001111", 18 => "00101110", 19 => "00000100", 
    20 => "00000110", 21 => "00011000", 22 => "00011111", 23 => "11010110", 
    24 => "11110101", 25 => "11110101", 26 => "11001011", 27 => "11110111", 
    28 => "00111100", 29 => "11100100", 30 => "11110101", 31 => "11111101");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

