-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity awn_forward_conv2_block_p_ZL2W2_3_0_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 7; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of awn_forward_conv2_block_p_ZL2W2_3_0_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "0000001", 1 => "1110011", 2 => "1111001", 3 => "1110010", 
    4 => "0011100", 5 => "0000001", 6 => "0000111", 7 => "0111010", 
    8 => "1110000", 9 => "0010001", 10 => "0000001", 11 => "1111110", 
    12 => "1100111", 13 => "1110110", 14 => "0010001", 15 => "1111100", 
    16 => "1111101", 17 => "0001010", 18 => "1111010", 19 => "1100000", 
    20 => "1011100", 21 => "1110111", 22 => "1110110", 23 => "0000110", 
    24 => "1111000", 25 => "1110000", 26 => "1100111", 27 => "1111100", 
    28 => "1100111", 29 => "1110010", 30 => "1110101", 31 => "0100100", 
    32 => "0000101", 33 => "1110010", 34 => "0001100", 35 => "0101000", 
    36 => "0000001", 37 => "1011001", 38 => "0001011", 39 => "1010100", 
    40 => "0010010", 41 => "0000010", 42 => "1100101", 43 => "0001110", 
    44 => "0101100", 45 => "0000010", 46 => "1110111", 47 => "1110101", 
    48 => "0011111", 49 => "0001101", 50 => "0100000", 51 => "1110110", 
    52 => "0100011", 53 => "1010101", 54 => "0010001", 55 => "0001101", 
    56 => "0000110", 57 => "1110100", 58 => "1011010", 59 => "1110000", 
    60 => "1111010", 61 => "1111000", 62 => "1111100", 63 => "1111011");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

