-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity awn_forward_conv2_block_p_ZL2W2_0_18_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of awn_forward_conv2_block_p_ZL2W2_0_18_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "11101000", 1 => "11100010", 2 => "00111001", 3 => "11111101", 
    4 => "11110111", 5 => "11010111", 6 => "00010100", 7 => "11111101", 
    8 => "00010100", 9 => "00010011", 10 => "00011011", 11 => "00010111", 
    12 => "11101100", 13 => "11110111", 14 => "11110011", 15 => "11100000", 
    16 => "11100010", 17 => "00001010", 18 => "00000101", 19 => "11101100", 
    20 => "00000110", 21 => "11101110", 22 => "00100011", 23 => "00000011", 
    24 => "11110100", 25 => "11111110", 26 => "10111010", 27 => "00000111", 
    28 => "00000011", 29 => "00000101", 30 => "00010000", 31 => "11111011", 
    32 => "11111000", 33 => "00001010", 34 => "00100011", 35 => "11110010", 
    36 => "00001000", 37 => "11111010", 38 => "00001111", 39 => "00101000", 
    40 => "00001111", 41 => "00000111", 42 => "00000000", 43 => "11011011", 
    44 => "00001101", 45 => "11111100", 46 => "00000010", 47 => "11101100", 
    48 => "11011010", 49 => "11110110", 50 => "11111001", 51 => "00011101", 
    52 => "00010110", 53 => "00101000", 54 => "11010100", 55 => "11101111", 
    56 => "11111100", 57 => "00001101", 58 => "11100000", 59 => "00001111", 
    60 => "11100001", 61 => "11111010", 62 => "11010111", 63 => "11111101");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

