-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity awn_forward_conv2_block_p_ZL2W2_1_18_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of awn_forward_conv2_block_p_ZL2W2_1_18_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "11010110", 1 => "00000111", 2 => "00010110", 3 => "00100110", 
    4 => "11111111", 5 => "11111001", 6 => "00001111", 7 => "00010000", 
    8 => "11110001", 9 => "11111111", 10 => "11101101", 11 => "00001110", 
    12 => "11110101", 13 => "00000011", 14 => "00000010", 15 => "11110100", 
    16 => "00000110", 17 => "11010110", 18 => "11100000", 19 => "00000001", 
    20 => "11111001", 21 => "00000000", 22 => "00101010", 23 => "00000111", 
    24 => "00000101", 25 => "11100110", 26 => "11111001", 27 => "00000101", 
    28 => "00010110", 29 => "11101111", 30 => "00110001", 31 => "11101100", 
    32 => "11111010", 33 => "00001000", 34 => "00010101", 35 => "00001100", 
    36 => "11110100", 37 => "11011010", 38 => "00010101", 39 => "01000100", 
    40 => "00000000", 41 => "11111111", 42 => "00001100", 43 => "11001000", 
    44 => "00000011", 45 => "11001010", 46 => "00000100", 47 => "11101110", 
    48 => "11011110", 49 => "00011011", 50 => "11110100", 51 => "11011010", 
    52 => "00010011", 53 => "11101100", 54 => "11111001", 55 => "11111001", 
    56 => "00011010", 57 => "00000001", 58 => "00001001", 59 => "00010010", 
    60 => "11101011", 61 => "11111001", 62 => "00001000", 63 => "11111110");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

