-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity awn_forward_conv2_block_p_ZL2W2_2_53_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 7; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of awn_forward_conv2_block_p_ZL2W2_2_53_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "0000001", 1 => "1110000", 2 => "0011011", 3 => "1111100", 
    4 => "1111001", 5 => "1110101", 6 => "0000000", 7 => "1111001", 
    8 => "1111000", 9 => "0000111", 10 => "0010010", 11 => "0001111", 
    12 => "1101001", 13 => "0000000", 14 => "0001100", 15 => "0000000", 
    16 => "0000010", 17 => "1100010", 18 => "0001101", 19 => "1100010", 
    20 => "1111101", 21 => "1111110", 22 => "1110111", 23 => "0001010", 
    24 => "1011000", 25 => "1101001", 26 => "0000011", 27 => "0001100", 
    28 => "1101110", 29 => "0000110", 30 => "0000010", 31 => "0110000", 
    32 => "1111011", 33 => "0000000", 34 => "1100111", 35 => "1110001", 
    36 => "1111100", 37 => "1101110", 38 => "1111101", 39 => "1101111", 
    40 => "0100000", 41 => "1110001", 42 => "0000010", 43 => "0011010", 
    44 => "0010100", 45 => "0101100", 46 => "1101100", 47 => "1101111", 
    48 => "0100110", 49 => "0000010", 50 => "0011011", 51 => "0000101", 
    52 => "0001111", 53 => "0001010", 54 => "1111111", 55 => "0100001", 
    56 => "1101000", 57 => "1101100", 58 => "1111000", 59 => "0110001", 
    60 => "1111111", 61 => "0001110", 62 => "1110100", 63 => "0010111");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

