-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity awn_forward_conv2_block_p_ZL2W2_4_43_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of awn_forward_conv2_block_p_ZL2W2_4_43_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00001111", 1 => "00000101", 2 => "00101011", 3 => "00011111", 
    4 => "00001000", 5 => "00001000", 6 => "11111001", 7 => "00111001", 
    8 => "00011101", 9 => "00000000", 10 => "00010010", 11 => "00001001", 
    12 => "11111111", 13 => "11111000", 14 => "11011001", 15 => "00001110", 
    16 => "00111111", 17 => "11010011", 18 => "11100100", 19 => "11011011", 
    20 => "11000101", 21 => "11100001", 22 => "11100001", 23 => "00000010", 
    24 => "11110001", 25 => "11111011", 26 => "00010010", 27 => "00010010", 
    28 => "00000001", 29 => "00010010", 30 => "00110101", 31 => "00000010", 
    32 => "00010111", 33 => "10100100", 34 => "00000110", 35 => "11011100", 
    36 => "00011001", 37 => "11110101", 38 => "11001111", 39 => "00001111", 
    40 => "00001101", 41 => "00000000", 42 => "00000011", 43 => "00000001", 
    44 => "11110101", 45 => "00001001", 46 => "11101001", 47 => "00000011", 
    48 => "00011101", 49 => "00010011", 50 => "00110001", 51 => "00001101", 
    52 => "11111100", 53 => "00101001", 54 => "00000111", 55 => "00101011", 
    56 => "11110110", 57 => "00010111", 58 => "11110111", 59 => "00000000", 
    60 => "11111100", 61 => "11101000", 62 => "00010011", 63 => "00100110");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

