-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity awn_forward_linear_acc_32_128_Pipeline_VITIS_LOOP_186_1_p_ZL4Wse0_93_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 7; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of awn_forward_linear_acc_32_128_Pipeline_VITIS_LOOP_186_1_p_ZL4Wse0_93_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "0010001", 1 => "0110000", 2 => "0100011", 3 => "0011100", 
    4 => "1110101", 5 => "0010100", 6 => "0011001", 7 => "0110111", 
    8 => "0010101", 9 => "0010000", 10 => "1111111", 11 => "0011000", 
    12 => "0001110", 13 => "0011010", 14 => "1100010", 15 => "0100000", 
    16 => "0010011", 17 => "0001101", 18 => "1101011", 19 => "0010000", 
    20 => "1110100", 21 => "0010011", 22 => "0100000", 23 => "0000111", 
    24 => "0100110", 25 => "0001100", 26 => "0000111", 27 => "1110101", 
    28 => "0011111", 29 => "1101101", 30 => "0010001", 31 => "0011010");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

