-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity awn_forward_linear_acc_32_128_Pipeline_VITIS_LOOP_186_1_p_ZL4Wse0_83_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 7; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of awn_forward_linear_acc_32_128_Pipeline_VITIS_LOOP_186_1_p_ZL4Wse0_83_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "0110101", 1 => "0101011", 2 => "0100101", 3 => "1111011", 
    4 => "0001101", 5 => "0110001", 6 => "0101000", 7 => "0100100", 
    8 => "0101011", 9 => "0110100", 10 => "1111000", 11 => "0101011", 
    12 => "1110100", 13 => "0101110", 14 => "1110101", 15 => "0001001", 
    16 => "0010000", 17 => "1111101", 18 => "0010100", 19 => "0101000", 
    20 => "0000110", 21 => "0011100", 22 => "0010011", 23 => "0000011", 
    24 => "0100000", 25 => "1111011", 26 => "0100010", 27 => "0010110", 
    28 => "0011111", 29 => "1110010", 30 => "0000000", 31 => "0001110");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

