-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity awn_forward_conv2_block_p_ZL2W2_2_22_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of awn_forward_conv2_block_p_ZL2W2_2_22_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "11110011", 1 => "00001110", 2 => "00001110", 3 => "00000011", 
    4 => "11111110", 5 => "00010010", 6 => "11110100", 7 => "00010101", 
    8 => "00001100", 9 => "00000001", 10 => "00101011", 11 => "11110100", 
    12 => "11110100", 13 => "11111010", 14 => "11101100", 15 => "00000100", 
    16 => "00011111", 17 => "10111010", 18 => "11111010", 19 => "11101001", 
    20 => "11110100", 21 => "11111110", 22 => "11110100", 23 => "00000101", 
    24 => "00110011", 25 => "11110110", 26 => "00010100", 27 => "11100110", 
    28 => "00000111", 29 => "00001100", 30 => "11111110", 31 => "00000011", 
    32 => "00001000", 33 => "11111000", 34 => "11011111", 35 => "11110000", 
    36 => "11110110", 37 => "00011111", 38 => "11111111", 39 => "11111011", 
    40 => "00001110", 41 => "11110010", 42 => "11101101", 43 => "00001010", 
    44 => "11110011", 45 => "00101001", 46 => "00001010", 47 => "11110000", 
    48 => "00101110", 49 => "00001010", 50 => "00001000", 51 => "11011110", 
    52 => "11010111", 53 => "00010010", 54 => "11111011", 55 => "00101100", 
    56 => "00000000", 57 => "11110010", 58 => "00001101", 59 => "11110111", 
    60 => "00000010", 61 => "11101111", 62 => "00001011", 63 => "00010101");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

