-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity awn_forward_conv2_block_p_ZL2W2_2_40_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 7; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of awn_forward_conv2_block_p_ZL2W2_2_40_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "1111101", 1 => "0001000", 2 => "0010001", 3 => "1100100", 
    4 => "0000011", 5 => "1100110", 6 => "1100100", 7 => "0000100", 
    8 => "1101001", 9 => "1101010", 10 => "0101001", 11 => "0001011", 
    12 => "0010000", 13 => "0010000", 14 => "1111100", 15 => "0001110", 
    16 => "1010100", 17 => "0001101", 18 => "0000010", 19 => "0000101", 
    20 => "0000110", 21 => "0000100", 22 => "1110111", 23 => "1100000", 
    24 => "0100110", 25 => "1110010", 26 => "1111001", 27 => "1110001", 
    28 => "1101010", 29 => "1101011", 30 => "1110110", 31 => "0010011", 
    32 => "1111100", 33 => "0000011", 34 => "1100101", 35 => "0010010", 
    36 => "0000110", 37 => "0001100", 38 => "1110010", 39 => "0000100", 
    40 => "1011000", 41 => "1111010", 42 => "1111011", 43 => "0001010", 
    44 => "0001111", 45 => "1111101", 46 => "0000100", 47 => "1111000", 
    48 => "0001010", 49 => "0000010", 50 => "0000111", 51 => "0000010", 
    52 => "0110010", 53 => "1000011", 54 => "0100101", 55 => "0100100", 
    56 => "1111100", 57 => "1010110", 58 => "0101011", 59 => "0011000", 
    60 => "0000100", 61 => "0010001", 62 => "1101110", 63 => "0001001");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

