-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity awn_forward_conv2_block_p_ZL2W2_1_46_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 7; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of awn_forward_conv2_block_p_ZL2W2_1_46_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "1111011", 1 => "1001110", 2 => "0000101", 3 => "1011111", 
    4 => "1011111", 5 => "0000010", 6 => "0000000", 7 => "0001011", 
    8 => "1111010", 9 => "0000011", 10 => "0001010", 11 => "0011011", 
    12 => "1110111", 13 => "1011010", 14 => "0000000", 15 => "0011111", 
    16 => "1101111", 17 => "1010000", 18 => "0000001", 19 => "0000000", 
    20 => "0000101", 21 => "1110101", 22 => "1111010", 23 => "0001110", 
    24 => "1001001", 25 => "0000111", 26 => "0001000", 27 => "1101111", 
    28 => "1110100", 29 => "1111111", 30 => "0000000", 31 => "0010110", 
    32 => "0000001", 33 => "0000001", 34 => "1110100", 35 => "1111001", 
    36 => "0001100", 37 => "1100101", 38 => "0000111", 39 => "1010000", 
    40 => "0011001", 41 => "0000110", 42 => "0000010", 43 => "0001100", 
    44 => "1010111", 45 => "0110100", 46 => "1110110", 47 => "1110110", 
    48 => "0010111", 49 => "0001100", 50 => "1101101", 51 => "1110110", 
    52 => "0011110", 53 => "0011001", 54 => "1100101", 55 => "0011110", 
    56 => "1110001", 57 => "1111100", 58 => "0000010", 59 => "0011001", 
    60 => "0001100", 61 => "0010100", 62 => "1111110", 63 => "0010111");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

