-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity awn_forward_conv2_block_p_ZL2W2_2_54_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of awn_forward_conv2_block_p_ZL2W2_2_54_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "11101110", 1 => "00011011", 2 => "00010000", 3 => "00001111", 
    4 => "00011111", 5 => "00001101", 6 => "11110110", 7 => "00001111", 
    8 => "00010000", 9 => "00001110", 10 => "10100001", 11 => "11100000", 
    12 => "00001111", 13 => "00100000", 14 => "11101011", 15 => "00000101", 
    16 => "00001110", 17 => "11111110", 18 => "11101001", 19 => "11101110", 
    20 => "11110010", 21 => "11101010", 22 => "11101100", 23 => "11110000", 
    24 => "00000001", 25 => "00000000", 26 => "11110001", 27 => "00000011", 
    28 => "00011111", 29 => "00001100", 30 => "00001110", 31 => "00000100", 
    32 => "00011000", 33 => "11101000", 34 => "11101011", 35 => "11110101", 
    36 => "11111110", 37 => "00001101", 38 => "11110010", 39 => "00010100", 
    40 => "11110101", 41 => "11110101", 42 => "00000111", 43 => "00000010", 
    44 => "00010000", 45 => "00101110", 46 => "00001100", 47 => "11111110", 
    48 => "00001001", 49 => "00100000", 50 => "11111000", 51 => "11111010", 
    52 => "11111011", 53 => "00110010", 54 => "11101100", 55 => "11111000", 
    56 => "00000111", 57 => "11101100", 58 => "00000101", 59 => "11111111", 
    60 => "11110101", 61 => "11110101", 62 => "00011111", 63 => "00001101");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

