-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity awn_forward_conv2_block_p_ZL2W2_3_37_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 7; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of awn_forward_conv2_block_p_ZL2W2_3_37_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "0000100", 1 => "0011010", 2 => "1101101", 3 => "0011011", 
    4 => "0000010", 5 => "0010000", 6 => "0000110", 7 => "0100000", 
    8 => "1110110", 9 => "1101011", 10 => "1110110", 11 => "0000110", 
    12 => "0010000", 13 => "0011010", 14 => "0001100", 15 => "0011100", 
    16 => "0011011", 17 => "1011111", 18 => "0010001", 19 => "1111011", 
    20 => "1111110", 21 => "1111111", 22 => "1101100", 23 => "1111001", 
    24 => "0000000", 25 => "0010101", 26 => "0011010", 27 => "1010100", 
    28 => "1111010", 29 => "0010001", 30 => "1011101", 31 => "1110000", 
    32 => "0100010", 33 => "1110001", 34 => "1100101", 35 => "1111110", 
    36 => "1101101", 37 => "1001110", 38 => "0001100", 39 => "0001111", 
    40 => "0000110", 41 => "1111111", 42 => "1100101", 43 => "1000001", 
    44 => "0001101", 45 => "1001010", 46 => "1110101", 47 => "1110110", 
    48 => "0000000", 49 => "0011111", 50 => "0001010", 51 => "1010000", 
    52 => "0011100", 53 => "1111010", 54 => "0011110", 55 => "0110010", 
    56 => "0101010", 57 => "1101101", 58 => "1111111", 59 => "1110001", 
    60 => "0010001", 61 => "0010111", 62 => "0011010", 63 => "0010111");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

