-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity awn_forward_conv2_block_p_ZL2W2_2_37_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of awn_forward_conv2_block_p_ZL2W2_2_37_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00010000", 1 => "11110000", 2 => "11111110", 3 => "00000010", 
    4 => "00000001", 5 => "00001110", 6 => "11100100", 7 => "00000101", 
    8 => "11110110", 9 => "00001001", 10 => "11111100", 11 => "00010101", 
    12 => "00001010", 13 => "11111001", 14 => "00001001", 15 => "00000110", 
    16 => "00000100", 17 => "11011110", 18 => "00010011", 19 => "00010101", 
    20 => "11111100", 21 => "00001100", 22 => "00010100", 23 => "11111110", 
    24 => "00010111", 25 => "00010010", 26 => "11110011", 27 => "10110010", 
    28 => "00010101", 29 => "11111111", 30 => "11100111", 31 => "11101111", 
    32 => "11011100", 33 => "11101011", 34 => "11101101", 35 => "00101011", 
    36 => "11101101", 37 => "11110101", 38 => "00011000", 39 => "00011111", 
    40 => "11111110", 41 => "00000100", 42 => "11111000", 43 => "00000100", 
    44 => "11101011", 45 => "11100010", 46 => "00010010", 47 => "00000100", 
    48 => "11001010", 49 => "11111010", 50 => "11101001", 51 => "11000111", 
    52 => "00011000", 53 => "00000001", 54 => "00010111", 55 => "00001000", 
    56 => "11110100", 57 => "00000110", 58 => "00110011", 59 => "11110011", 
    60 => "00000101", 61 => "00001101", 62 => "00010011", 63 => "00101000");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

