-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity awn_forward_conv2_block_p_ZL2W2_0_7_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of awn_forward_conv2_block_p_ZL2W2_0_7_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "11011000", 1 => "11101111", 2 => "11110000", 3 => "11110110", 
    4 => "11111001", 5 => "11111011", 6 => "00010001", 7 => "00010000", 
    8 => "11100111", 9 => "11111111", 10 => "00011111", 11 => "11110111", 
    12 => "11111001", 13 => "11101100", 14 => "11101110", 15 => "00001110", 
    16 => "11101111", 17 => "11101110", 18 => "11110010", 19 => "00001000", 
    20 => "00001001", 21 => "11101100", 22 => "00000000", 23 => "11010010", 
    24 => "11011110", 25 => "00001011", 26 => "00000010", 27 => "00010110", 
    28 => "00011000", 29 => "11110011", 30 => "11111101", 31 => "11111000", 
    32 => "11111000", 33 => "00001110", 34 => "11111100", 35 => "11110101", 
    36 => "11100111", 37 => "11010011", 38 => "11010101", 39 => "01001100", 
    40 => "11001101", 41 => "11100100", 42 => "11111110", 43 => "11101110", 
    44 => "00000100", 45 => "00100101", 46 => "00011110", 47 => "00000001", 
    48 => "11111111", 49 => "00001111", 50 => "11110101", 51 => "11101001", 
    52 => "11111110", 53 => "11100010", 54 => "11000110", 55 => "00010000", 
    56 => "00011010", 57 => "11110001", 58 => "11111111", 59 => "00001001", 
    60 => "11111101", 61 => "00001001", 62 => "00000010", 63 => "00001110");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

