-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity awn_forward_conv2_block_p_ZL2W2_0_2_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of awn_forward_conv2_block_p_ZL2W2_0_2_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00011101", 1 => "11110100", 2 => "10111001", 3 => "00001001", 
    4 => "00000011", 5 => "00000100", 6 => "00000011", 7 => "00101111", 
    8 => "00000010", 9 => "11100001", 10 => "00011010", 11 => "00010010", 
    12 => "00010001", 13 => "11110011", 14 => "00011110", 15 => "00100001", 
    16 => "00001111", 17 => "00001100", 18 => "00100100", 19 => "00011011", 
    20 => "11001010", 21 => "00010000", 22 => "11101110", 23 => "00000101", 
    24 => "00100111", 25 => "00000111", 26 => "11101011", 27 => "11101000", 
    28 => "11100110", 29 => "11110011", 30 => "11011001", 31 => "00011000", 
    32 => "11101110", 33 => "11101101", 34 => "00001111", 35 => "00001011", 
    36 => "00010001", 37 => "11110000", 38 => "00010010", 39 => "00101100", 
    40 => "00001100", 41 => "00010000", 42 => "11011011", 43 => "11101010", 
    44 => "11111000", 45 => "11100000", 46 => "11010111", 47 => "00001001", 
    48 => "11101010", 49 => "00011000", 50 => "11000110", 51 => "00000010", 
    52 => "00111010", 53 => "11100100", 54 => "00100100", 55 => "00001010", 
    56 => "11111001", 57 => "00001101", 58 => "00001011", 59 => "00010000", 
    60 => "11111101", 61 => "00000100", 62 => "11111001", 63 => "00011100");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

