-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity awn_forward_conv2_block_p_ZL2W2_3_30_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 7; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of awn_forward_conv2_block_p_ZL2W2_3_30_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "0001001", 1 => "0000101", 2 => "1100100", 3 => "1101110", 
    4 => "0001111", 5 => "0000010", 6 => "1111111", 7 => "0000000", 
    8 => "0100101", 9 => "0000000", 10 => "1010011", 11 => "1001001", 
    12 => "1111100", 13 => "1111111", 14 => "1111000", 15 => "0001010", 
    16 => "0010011", 17 => "1110001", 18 => "1110100", 19 => "0000010", 
    20 => "1110101", 21 => "1111111", 22 => "1110101", 23 => "0001100", 
    24 => "1010110", 25 => "1101010", 26 => "1100100", 27 => "1101110", 
    28 => "0001010", 29 => "0001001", 30 => "0000000", 31 => "0100010", 
    32 => "1101100", 33 => "0000000", 34 => "1111010", 35 => "1110011", 
    36 => "1111011", 37 => "0000010", 38 => "0001111", 39 => "1110000", 
    40 => "0001111", 41 => "1111011", 42 => "0000110", 43 => "1111100", 
    44 => "1101101", 45 => "1101001", 46 => "0000000", 47 => "0000100", 
    48 => "0110001", 49 => "0000010", 50 => "1111100", 51 => "1111110", 
    52 => "1010000", 53 => "0001000", 54 => "1111000", 55 => "0001100", 
    56 => "1101101", 57 => "0000111", 58 => "1110011", 59 => "1001111", 
    60 => "1100001", 61 => "1101110", 62 => "0000100", 63 => "0100100");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

