-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity awn_forward_conv2_block_p_ZL2W2_0_46_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 7; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of awn_forward_conv2_block_p_ZL2W2_0_46_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "0011000", 1 => "1000101", 2 => "1111010", 3 => "1010100", 
    4 => "1100000", 5 => "1111111", 6 => "0001011", 7 => "0001010", 
    8 => "1110111", 9 => "1110110", 10 => "0010001", 11 => "0001001", 
    12 => "1100100", 13 => "1001110", 14 => "0000110", 15 => "0000110", 
    16 => "1111011", 17 => "1101001", 18 => "1111101", 19 => "0000000", 
    20 => "0000010", 21 => "1111100", 22 => "1111111", 23 => "0000100", 
    24 => "1010100", 25 => "1111000", 26 => "0010111", 27 => "0001010", 
    28 => "1000110", 29 => "1111100", 30 => "0000111", 31 => "1111001", 
    32 => "0011001", 33 => "0000000", 34 => "0001000", 35 => "1011001", 
    36 => "0010111", 37 => "1111011", 38 => "0001011", 39 => "0000000", 
    40 => "0010100", 41 => "0001101", 42 => "1110010", 43 => "1111101", 
    44 => "1011110", 45 => "0111111", 46 => "1100101", 47 => "1101010", 
    48 => "0000000", 49 => "0001100", 50 => "1010000", 51 => "1111111", 
    52 => "0000111", 53 => "0001011", 54 => "1111110", 55 => "0011111", 
    56 => "1111111", 57 => "0001001", 58 => "0001000", 59 => "0001110", 
    60 => "0000010", 61 => "0001110", 62 => "1110101", 63 => "0000110");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

