-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity awn_forward_conv2_block_p_ZL2W2_2_41_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 7; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of awn_forward_conv2_block_p_ZL2W2_2_41_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "1110100", 1 => "1111001", 2 => "0000111", 3 => "1110011", 
    4 => "0001011", 5 => "0001001", 6 => "1010110", 7 => "0000000", 
    8 => "0000010", 9 => "0001011", 10 => "0001110", 11 => "0001101", 
    12 => "0001100", 13 => "1111011", 14 => "0000010", 15 => "0001011", 
    16 => "0011111", 17 => "0011101", 18 => "0001001", 19 => "1111110", 
    20 => "0000100", 21 => "1111101", 22 => "0001000", 23 => "1111001", 
    24 => "0001110", 25 => "0000011", 26 => "0000001", 27 => "1001110", 
    28 => "0100011", 29 => "0001100", 30 => "0000101", 31 => "1100100", 
    32 => "1011100", 33 => "0001011", 34 => "0100100", 35 => "0010011", 
    36 => "1101110", 37 => "1110011", 38 => "0001111", 39 => "1010110", 
    40 => "0000100", 41 => "0010011", 42 => "0010001", 43 => "1001010", 
    44 => "1111001", 45 => "0000001", 46 => "0100101", 47 => "0000110", 
    48 => "1101010", 49 => "0100100", 50 => "0000100", 51 => "0000001", 
    52 => "0010010", 53 => "0101100", 54 => "1110110", 55 => "1111000", 
    56 => "0001001", 57 => "0010010", 58 => "0001101", 59 => "0100011", 
    60 => "1111101", 61 => "0000110", 62 => "0000100", 63 => "1101011");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

