-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity awn_forward_conv2_block_p_ZL2W2_2_26_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 7; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of awn_forward_conv2_block_p_ZL2W2_2_26_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "0010111", 1 => "1111100", 2 => "1100100", 3 => "0000011", 
    4 => "1111111", 5 => "1111010", 6 => "1111111", 7 => "1111111", 
    8 => "1110000", 9 => "1101111", 10 => "1110001", 11 => "0001010", 
    12 => "1110001", 13 => "1101110", 14 => "0011110", 15 => "0011000", 
    16 => "0100001", 17 => "1010101", 18 => "0001010", 19 => "0011000", 
    20 => "1110001", 21 => "0010111", 22 => "1111100", 23 => "0001001", 
    24 => "1010100", 25 => "0010011", 26 => "0001101", 27 => "1110101", 
    28 => "1110000", 29 => "0000001", 30 => "0000101", 31 => "0100010", 
    32 => "1111001", 33 => "1111010", 34 => "1111010", 35 => "1111001", 
    36 => "0000010", 37 => "1110010", 38 => "0001010", 39 => "1001100", 
    40 => "1111111", 41 => "0000010", 42 => "1111011", 43 => "0000110", 
    44 => "0001111", 45 => "1111110", 46 => "1110001", 47 => "1111111", 
    48 => "0010110", 49 => "0001011", 50 => "1111001", 51 => "1101101", 
    52 => "0000100", 53 => "1100001", 54 => "0000011", 55 => "0100100", 
    56 => "0000111", 57 => "1111110", 58 => "1111011", 59 => "0100101", 
    60 => "0000101", 61 => "0000001", 62 => "1111111", 63 => "0011010");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

