-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity awn_forward_conv2_block_p_ZL2W2_0_4_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of awn_forward_conv2_block_p_ZL2W2_0_4_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "11001110", 1 => "00000010", 2 => "00100001", 3 => "11011110", 
    4 => "00010100", 5 => "11011010", 6 => "00000111", 7 => "00001011", 
    8 => "00000001", 9 => "00000010", 10 => "01010100", 11 => "11111110", 
    12 => "11100100", 13 => "00001100", 14 => "11110010", 15 => "11110111", 
    16 => "00010000", 17 => "11010100", 18 => "11111110", 19 => "11110011", 
    20 => "00011000", 21 => "00000111", 22 => "00011001", 23 => "11101101", 
    24 => "00000000", 25 => "11010100", 26 => "10110010", 27 => "00010000", 
    28 => "11111100", 29 => "00000011", 30 => "00011100", 31 => "00001000", 
    32 => "00000101", 33 => "11111010", 34 => "00000010", 35 => "11011000", 
    36 => "00001110", 37 => "00000000", 38 => "11111011", 39 => "00100001", 
    40 => "00000000", 41 => "11110110", 42 => "11110110", 43 => "11101100", 
    44 => "11101101", 45 => "11111100", 46 => "11101000", 47 => "11101101", 
    48 => "00000100", 49 => "00001010", 50 => "00001001", 51 => "11011110", 
    52 => "11111101", 53 => "00010011", 54 => "11100101", 55 => "00000100", 
    56 => "00011011", 57 => "00010101", 58 => "11110110", 59 => "11111010", 
    60 => "11110100", 61 => "11100101", 62 => "11011010", 63 => "00011110");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

