-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity awn_forward_conv2_block_p_ZL2W2_4_42_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 7; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of awn_forward_conv2_block_p_ZL2W2_4_42_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "1111011", 1 => "0001010", 2 => "0001100", 3 => "1110011", 
    4 => "0000011", 5 => "0010101", 6 => "1110101", 7 => "0000111", 
    8 => "1111111", 9 => "1111010", 10 => "0100000", 11 => "0000011", 
    12 => "1111100", 13 => "0000110", 14 => "0000100", 15 => "0000000", 
    16 => "0101011", 17 => "0001000", 18 => "0001010", 19 => "1111001", 
    20 => "1100111", 21 => "0010100", 22 => "1101011", 23 => "0000010", 
    24 => "0111101", 25 => "0001101", 26 => "0100010", 27 => "1011011", 
    28 => "0101000", 29 => "0001100", 30 => "1111011", 31 => "1111000", 
    32 => "0001010", 33 => "1101110", 34 => "0000000", 35 => "1010001", 
    36 => "0000110", 37 => "1110000", 38 => "0010000", 39 => "0011000", 
    40 => "1111010", 41 => "1011000", 42 => "1101001", 43 => "1110001", 
    44 => "1111110", 45 => "1111011", 46 => "0000010", 47 => "1111100", 
    48 => "0011001", 49 => "0001100", 50 => "0001101", 51 => "1100111", 
    52 => "1000110", 53 => "0001111", 54 => "0000010", 55 => "0011101", 
    56 => "0000010", 57 => "1001011", 58 => "0000111", 59 => "1011100", 
    60 => "1111011", 61 => "0000100", 62 => "0010010", 63 => "0001111");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

