-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity awn_forward_conv2_block_p_ZL2W2_2_19_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 7; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of awn_forward_conv2_block_p_ZL2W2_2_19_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "1101110", 1 => "0010001", 2 => "0010100", 3 => "1110111", 
    4 => "0000001", 5 => "0001110", 6 => "1110000", 7 => "1111010", 
    8 => "1110000", 9 => "1110010", 10 => "0000101", 11 => "0010100", 
    12 => "0010010", 13 => "0010011", 14 => "1110110", 15 => "0010000", 
    16 => "1100001", 17 => "1101110", 18 => "1111001", 19 => "0001001", 
    20 => "1111000", 21 => "0001110", 22 => "1110101", 23 => "1111010", 
    24 => "1111110", 25 => "1111110", 26 => "0000001", 27 => "1111001", 
    28 => "0011110", 29 => "0001011", 30 => "0000001", 31 => "1001111", 
    32 => "0000100", 33 => "0000011", 34 => "0001111", 35 => "0001110", 
    36 => "1111101", 37 => "1110011", 38 => "0010010", 39 => "0111010", 
    40 => "1111000", 41 => "0001101", 42 => "1111111", 43 => "0010001", 
    44 => "1111000", 45 => "1111100", 46 => "1111001", 47 => "0010010", 
    48 => "1100101", 49 => "0010110", 50 => "1110001", 51 => "0000000", 
    52 => "1100111", 53 => "1101100", 54 => "0001111", 55 => "0000101", 
    56 => "0010001", 57 => "0010110", 58 => "0011011", 59 => "1110100", 
    60 => "0001100", 61 => "0001000", 62 => "0000001", 63 => "1101100");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

