-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity awn_forward_conv2_block_p_ZL2W2_1_34_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of awn_forward_conv2_block_p_ZL2W2_1_34_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "11101000", 1 => "00001010", 2 => "11101111", 3 => "00010110", 
    4 => "00000010", 5 => "11111101", 6 => "11011011", 7 => "00001110", 
    8 => "00001111", 9 => "11110111", 10 => "11010111", 11 => "00001011", 
    12 => "00001010", 13 => "00000011", 14 => "11111010", 15 => "00000100", 
    16 => "11011001", 17 => "00000101", 18 => "11101101", 19 => "00001011", 
    20 => "00010110", 21 => "00000010", 22 => "00001001", 23 => "00000001", 
    24 => "00010000", 25 => "00010010", 26 => "00001000", 27 => "10111110", 
    28 => "00010110", 29 => "00001001", 30 => "00101001", 31 => "00000100", 
    32 => "00001010", 33 => "00101101", 34 => "10111000", 35 => "11110011", 
    36 => "11111010", 37 => "00000001", 38 => "11101010", 39 => "10101010", 
    40 => "11111111", 41 => "00010101", 42 => "00001110", 43 => "00001001", 
    44 => "00000100", 45 => "00101101", 46 => "11100001", 47 => "00000100", 
    48 => "11101110", 49 => "00001011", 50 => "00001010", 51 => "11110111", 
    52 => "11011101", 53 => "00010100", 54 => "00101001", 55 => "00011000", 
    56 => "10111101", 57 => "11110000", 58 => "11011110", 59 => "11101100", 
    60 => "00001111", 61 => "11111000", 62 => "11111011", 63 => "00001010");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

