-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity awn_forward_conv2_block_p_ZL2W2_1_14_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of awn_forward_conv2_block_p_ZL2W2_1_14_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00000100", 1 => "11111001", 2 => "11110111", 3 => "00001111", 
    4 => "11111110", 5 => "11001011", 6 => "11111011", 7 => "11111101", 
    8 => "11110000", 9 => "11101101", 10 => "00000110", 11 => "11011000", 
    12 => "00001011", 13 => "11111100", 14 => "00001101", 15 => "00100101", 
    16 => "11111000", 17 => "11101010", 18 => "00100101", 19 => "00100100", 
    20 => "11100111", 21 => "00101001", 22 => "00001110", 23 => "00001110", 
    24 => "00011001", 25 => "00001100", 26 => "00001010", 27 => "11011010", 
    28 => "00010001", 29 => "11100011", 30 => "11100100", 31 => "00001110", 
    32 => "00000101", 33 => "11110110", 34 => "00001101", 35 => "00011001", 
    36 => "00000011", 37 => "00100101", 38 => "00101100", 39 => "00011101", 
    40 => "00001001", 41 => "00000101", 42 => "00010011", 43 => "00001110", 
    44 => "00001110", 45 => "11001100", 46 => "00001010", 47 => "00010111", 
    48 => "00101101", 49 => "00010011", 50 => "11111001", 51 => "11111011", 
    52 => "10111111", 53 => "11101100", 54 => "00100100", 55 => "01010000", 
    56 => "00000000", 57 => "11100100", 58 => "00000011", 59 => "11100011", 
    60 => "00000000", 61 => "00011011", 62 => "11101110", 63 => "00100101");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

