-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity awn_forward_conv2_block_p_ZL2W2_2_63_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 7; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of awn_forward_conv2_block_p_ZL2W2_2_63_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "0000001", 1 => "1111000", 2 => "1111100", 3 => "1101111", 
    4 => "1110100", 5 => "0001010", 6 => "1110100", 7 => "0000001", 
    8 => "1110001", 9 => "0001100", 10 => "1110111", 11 => "0010110", 
    12 => "0000000", 13 => "1111100", 14 => "1101111", 15 => "1110011", 
    16 => "1011111", 17 => "1010110", 18 => "0000100", 19 => "0000100", 
    20 => "0000101", 21 => "0000100", 22 => "1110100", 23 => "1111010", 
    24 => "0000001", 25 => "0000111", 26 => "0010010", 27 => "1110001", 
    28 => "1110110", 29 => "0000000", 30 => "1111010", 31 => "1111111", 
    32 => "0001101", 33 => "0001000", 34 => "0011100", 35 => "0100000", 
    36 => "1110101", 37 => "0010111", 38 => "0010100", 39 => "0100011", 
    40 => "1011100", 41 => "0000100", 42 => "1111000", 43 => "1110011", 
    44 => "0010100", 45 => "1111110", 46 => "0011000", 47 => "0001100", 
    48 => "0001111", 49 => "0010011", 50 => "1110111", 51 => "0000101", 
    52 => "1111101", 53 => "1110010", 54 => "0011110", 55 => "0001000", 
    56 => "1101100", 57 => "0001100", 58 => "0011001", 59 => "0000000", 
    60 => "0000101", 61 => "0000100", 62 => "0000011", 63 => "1111101");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

