-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity awn_forward_conv2_block_p_ZL2W2_3_18_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 7; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of awn_forward_conv2_block_p_ZL2W2_3_18_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "0100011", 1 => "0000011", 2 => "1011010", 3 => "1111100", 
    4 => "0001001", 5 => "1100100", 6 => "0010110", 7 => "0100000", 
    8 => "1110011", 9 => "0001101", 10 => "1101000", 11 => "0001111", 
    12 => "1111111", 13 => "1111011", 14 => "0100101", 15 => "0001000", 
    16 => "0011010", 17 => "1110010", 18 => "1111010", 19 => "0000111", 
    20 => "0001000", 21 => "0001000", 22 => "0011111", 23 => "0000111", 
    24 => "0000100", 25 => "0000001", 26 => "0010101", 27 => "1110000", 
    28 => "1111101", 29 => "1111101", 30 => "0000001", 31 => "0000001", 
    32 => "1111111", 33 => "0000100", 34 => "1011100", 35 => "1110001", 
    36 => "0000010", 37 => "1100000", 38 => "0001010", 39 => "0111000", 
    40 => "0000001", 41 => "0010100", 42 => "0001101", 43 => "1111001", 
    44 => "0001010", 45 => "1111110", 46 => "1101101", 47 => "1111110", 
    48 => "0001001", 49 => "0110010", 50 => "0000110", 51 => "1110010", 
    52 => "0001010", 53 => "0010100", 54 => "0001101", 55 => "0000001", 
    56 => "0000010", 57 => "0000111", 58 => "1111100", 59 => "0000110", 
    60 => "1110000", 61 => "0000110", 62 => "1011100", 63 => "0011110");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

