-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity awn_forward_conv2_block_p_ZL2W2_1_16_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of awn_forward_conv2_block_p_ZL2W2_1_16_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "11001000", 1 => "00001110", 2 => "00010101", 3 => "11110010", 
    4 => "00001110", 5 => "11100010", 6 => "11110001", 7 => "00011011", 
    8 => "00010011", 9 => "00001110", 10 => "10001001", 11 => "00100000", 
    12 => "00000110", 13 => "00010111", 14 => "11101101", 15 => "11100010", 
    16 => "00010101", 17 => "00011000", 18 => "11110000", 19 => "11101101", 
    20 => "00000100", 21 => "00001100", 22 => "11110101", 23 => "00001000", 
    24 => "11100001", 25 => "00000110", 26 => "11111101", 27 => "11111111", 
    28 => "00000100", 29 => "00001011", 30 => "00000010", 31 => "11111111", 
    32 => "00001011", 33 => "00001101", 34 => "11110010", 35 => "11010111", 
    36 => "11110001", 37 => "11101101", 38 => "11111000", 39 => "11101101", 
    40 => "00100001", 41 => "00000110", 42 => "00001100", 43 => "00001001", 
    44 => "11110011", 45 => "00000101", 46 => "00000001", 47 => "11110100", 
    48 => "00000100", 49 => "11110011", 50 => "00101011", 51 => "11001101", 
    52 => "11111101", 53 => "11110001", 54 => "11101010", 55 => "00001111", 
    56 => "11110100", 57 => "11010110", 58 => "11110001", 59 => "00000001", 
    60 => "11111110", 61 => "11100011", 62 => "11110110", 63 => "00001101");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

