-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity awn_forward_conv2_block_p_ZL2W2_4_1_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of awn_forward_conv2_block_p_ZL2W2_4_1_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00011110", 1 => "00001111", 2 => "00010100", 3 => "11110010", 
    4 => "11110100", 5 => "11111010", 6 => "11101001", 7 => "00010110", 
    8 => "11011110", 9 => "11111100", 10 => "01001011", 11 => "00110000", 
    12 => "00000110", 13 => "00001100", 14 => "00000111", 15 => "00010011", 
    16 => "10110000", 17 => "11110010", 18 => "11111101", 19 => "00001010", 
    20 => "00000111", 21 => "00001001", 22 => "00010101", 23 => "00011101", 
    24 => "00111101", 25 => "11111010", 26 => "00101010", 27 => "11111111", 
    28 => "11111110", 29 => "11011111", 30 => "11101010", 31 => "00001101", 
    32 => "00000101", 33 => "00001110", 34 => "11000001", 35 => "11101100", 
    36 => "00010011", 37 => "00010010", 38 => "00000110", 39 => "00101001", 
    40 => "00010000", 41 => "00000001", 42 => "00000010", 43 => "00001100", 
    44 => "11100101", 45 => "00001000", 46 => "00001100", 47 => "00001101", 
    48 => "11111011", 49 => "00010000", 50 => "11111110", 51 => "00001000", 
    52 => "11110000", 53 => "11001100", 54 => "00110111", 55 => "00000110", 
    56 => "11100110", 57 => "00010001", 58 => "00010101", 59 => "00000000", 
    60 => "11111101", 61 => "00001101", 62 => "11111100", 63 => "00010011");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

