-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity awn_forward_conv2_block_p_ZL2W2_1_56_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 7; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of awn_forward_conv2_block_p_ZL2W2_1_56_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "1111100", 1 => "0000100", 2 => "0000011", 3 => "1110111", 
    4 => "1111110", 5 => "0000100", 6 => "0001000", 7 => "0001001", 
    8 => "0000010", 9 => "1101101", 10 => "1110011", 11 => "1010000", 
    12 => "0001001", 13 => "0000000", 14 => "0010001", 15 => "0101100", 
    16 => "0101111", 17 => "1100110", 18 => "0000011", 19 => "0001110", 
    20 => "1101111", 21 => "0000100", 22 => "1110101", 23 => "0001010", 
    24 => "1100101", 25 => "0010001", 26 => "0001111", 27 => "1110010", 
    28 => "1110101", 29 => "1111100", 30 => "1101110", 31 => "0011110", 
    32 => "1111001", 33 => "1110100", 34 => "0000010", 35 => "1111100", 
    36 => "1111010", 37 => "1101110", 38 => "1101101", 39 => "1011111", 
    40 => "0000101", 41 => "0001001", 42 => "0000000", 43 => "1101110", 
    44 => "0000110", 45 => "1110101", 46 => "1111011", 47 => "0011110", 
    48 => "0100111", 49 => "0001010", 50 => "1110110", 51 => "0000011", 
    52 => "1011110", 53 => "0001010", 54 => "1111011", 55 => "0101101", 
    56 => "1011010", 57 => "0010110", 58 => "0010000", 59 => "1101001", 
    60 => "0001001", 61 => "0001010", 62 => "0001000", 63 => "0100010");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

