-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity awn_forward_conv2_block_p_ZL2W2_0_41_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of awn_forward_conv2_block_p_ZL2W2_0_41_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "11010101", 1 => "00001001", 2 => "00011001", 3 => "00001001", 
    4 => "00001110", 5 => "00100001", 6 => "11010110", 7 => "00011011", 
    8 => "11111011", 9 => "00001011", 10 => "10101100", 11 => "00000001", 
    12 => "00010111", 13 => "00010111", 14 => "00001011", 15 => "00011010", 
    16 => "00100010", 17 => "11111001", 18 => "00011100", 19 => "00010011", 
    20 => "11100110", 21 => "00000110", 22 => "11100110", 23 => "00000101", 
    24 => "00110000", 25 => "00000011", 26 => "00100011", 27 => "11000110", 
    28 => "00100010", 29 => "00001010", 30 => "00001111", 31 => "11010001", 
    32 => "11101001", 33 => "11110000", 34 => "11110010", 35 => "00011001", 
    36 => "00001100", 37 => "00011100", 38 => "00101011", 39 => "11110011", 
    40 => "11111001", 41 => "00010011", 42 => "11111010", 43 => "11101110", 
    44 => "00001010", 45 => "00001001", 46 => "11110010", 47 => "00000101", 
    48 => "11011000", 49 => "11111110", 50 => "11100010", 51 => "11010111", 
    52 => "00100000", 53 => "11111011", 54 => "00001110", 55 => "00000001", 
    56 => "11000101", 57 => "11111001", 58 => "00101010", 59 => "00010011", 
    60 => "00000100", 61 => "00010000", 62 => "00000010", 63 => "00011110");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

