-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity awn_forward_conv2_block_p_ZL2W2_2_62_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of awn_forward_conv2_block_p_ZL2W2_2_62_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00100101", 1 => "11110011", 2 => "11110111", 3 => "11101011", 
    4 => "11111100", 5 => "00000101", 6 => "11101010", 7 => "11011010", 
    8 => "00010010", 9 => "11111100", 10 => "11011001", 11 => "00001010", 
    12 => "00010000", 13 => "00000111", 14 => "00000100", 15 => "00001011", 
    16 => "00000111", 17 => "00000101", 18 => "00000010", 19 => "00000110", 
    20 => "11111001", 21 => "11110111", 22 => "00000101", 23 => "00000001", 
    24 => "00001000", 25 => "00010011", 26 => "11010101", 27 => "11000111", 
    28 => "00110110", 29 => "00000000", 30 => "00000010", 31 => "10110100", 
    32 => "00011110", 33 => "11111011", 34 => "11101110", 35 => "00000101", 
    36 => "00011001", 37 => "00000110", 38 => "00000100", 39 => "00111101", 
    40 => "00001001", 41 => "00100101", 42 => "11111000", 43 => "11100011", 
    44 => "11011100", 45 => "00111110", 46 => "00000011", 47 => "00001101", 
    48 => "10011101", 49 => "00011011", 50 => "00001000", 51 => "00000101", 
    52 => "11100010", 53 => "00000011", 54 => "11110101", 55 => "00000100", 
    56 => "11111001", 57 => "00010010", 58 => "11101010", 59 => "11110111", 
    60 => "11110111", 61 => "00000011", 62 => "11101011", 63 => "11111001");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

