-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity awn_forward_conv2_block_p_ZL2W2_1_19_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 7; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of awn_forward_conv2_block_p_ZL2W2_1_19_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "1011101", 1 => "0010111", 2 => "0001110", 3 => "0001001", 
    4 => "0000100", 5 => "1110110", 6 => "0001110", 7 => "0010100", 
    8 => "0000110", 9 => "1110100", 10 => "0100101", 11 => "1111100", 
    12 => "0010001", 13 => "0010111", 14 => "1111010", 15 => "0010111", 
    16 => "1101110", 17 => "1110001", 18 => "1111001", 19 => "0000011", 
    20 => "1110111", 21 => "0010101", 22 => "0000111", 23 => "1111100", 
    24 => "0000010", 25 => "1101110", 26 => "1111000", 27 => "1110011", 
    28 => "0101110", 29 => "1111001", 30 => "0011010", 31 => "1111001", 
    32 => "1111000", 33 => "0000110", 34 => "1110110", 35 => "1110010", 
    36 => "1111000", 37 => "1111010", 38 => "0001000", 39 => "0010110", 
    40 => "1111011", 41 => "0000100", 42 => "0000011", 43 => "1101100", 
    44 => "0010010", 45 => "1110100", 46 => "0000100", 47 => "0000010", 
    48 => "0100011", 49 => "0100111", 50 => "0000111", 51 => "0001000", 
    52 => "1110100", 53 => "1111000", 54 => "1111110", 55 => "0011110", 
    56 => "1100011", 57 => "0001011", 58 => "0011010", 59 => "1111001", 
    60 => "1111111", 61 => "0000101", 62 => "1111000", 63 => "0001100");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

