-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity awn_forward_conv2_block_p_ZL2W2_0_61_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 7; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of awn_forward_conv2_block_p_ZL2W2_0_61_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "0010101", 1 => "1110111", 2 => "0000011", 3 => "1111101", 
    4 => "0000100", 5 => "0011010", 6 => "0010011", 7 => "0011101", 
    8 => "1110100", 9 => "1101111", 10 => "1000110", 11 => "0000100", 
    12 => "0000000", 13 => "0000010", 14 => "0010010", 15 => "1100110", 
    16 => "0001001", 17 => "1110110", 18 => "0000001", 19 => "1110011", 
    20 => "1001011", 21 => "1110001", 22 => "1011101", 23 => "0000001", 
    24 => "0011001", 25 => "0000010", 26 => "0001000", 27 => "0010001", 
    28 => "1001110", 29 => "1100001", 30 => "1110100", 31 => "1111111", 
    32 => "0001101", 33 => "1110111", 34 => "0001100", 35 => "0001111", 
    36 => "0011000", 37 => "1111001", 38 => "1101101", 39 => "0000010", 
    40 => "0001001", 41 => "0010010", 42 => "1110101", 43 => "0010000", 
    44 => "1010110", 45 => "0001010", 46 => "1110001", 47 => "1111110", 
    48 => "1010111", 49 => "0000011", 50 => "0000111", 51 => "0000011", 
    52 => "0110110", 53 => "1100011", 54 => "0100101", 55 => "0000010", 
    56 => "0000000", 57 => "1011100", 58 => "0000110", 59 => "0010101", 
    60 => "0010000", 61 => "1111001", 62 => "0010100", 63 => "0001111");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

