-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity awn_forward_conv2_block_p_ZL2W2_2_15_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 7; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of awn_forward_conv2_block_p_ZL2W2_2_15_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "1101100", 1 => "0001110", 2 => "0000110", 3 => "1110110", 
    4 => "0001000", 5 => "0010011", 6 => "1100100", 7 => "0000001", 
    8 => "0001011", 9 => "0001101", 10 => "0011011", 11 => "1110001", 
    12 => "0010100", 13 => "0010111", 14 => "1100100", 15 => "0001110", 
    16 => "0011000", 17 => "1010110", 18 => "0000001", 19 => "0000100", 
    20 => "0001000", 21 => "0011011", 22 => "0001001", 23 => "0001011", 
    24 => "1110101", 25 => "1111101", 26 => "1111000", 27 => "1010010", 
    28 => "0011000", 29 => "0010001", 30 => "0000100", 31 => "1111001", 
    32 => "0000011", 33 => "1111101", 34 => "1011100", 35 => "1101110", 
    36 => "1111010", 37 => "0001101", 38 => "1111001", 39 => "0111100", 
    40 => "0001100", 41 => "0000011", 42 => "1100111", 43 => "0001010", 
    44 => "1110100", 45 => "0001100", 46 => "0011010", 47 => "0001010", 
    48 => "0011000", 49 => "0001110", 50 => "0010100", 51 => "1110001", 
    52 => "1110001", 53 => "0001010", 54 => "0001000", 55 => "0001111", 
    56 => "1100111", 57 => "0001100", 58 => "1110111", 59 => "0000001", 
    60 => "0000110", 61 => "1111001", 62 => "1111010", 63 => "0010101");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

