-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity awn_forward_conv2_block_p_ZL2W2_0_31_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of awn_forward_conv2_block_p_ZL2W2_0_31_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "11111110", 1 => "11011100", 2 => "00001000", 3 => "11100001", 
    4 => "11101000", 5 => "11111011", 6 => "00000010", 7 => "11100100", 
    8 => "11111011", 9 => "11110111", 10 => "11101100", 11 => "00011110", 
    12 => "11111000", 13 => "11101111", 14 => "11111101", 15 => "00010111", 
    16 => "11010110", 17 => "11011100", 18 => "00001000", 19 => "00000111", 
    20 => "11111111", 21 => "11111111", 22 => "00000101", 23 => "00010001", 
    24 => "11000000", 25 => "00001010", 26 => "00011000", 27 => "11111010", 
    28 => "11101001", 29 => "11111000", 30 => "00001011", 31 => "00010011", 
    32 => "00001001", 33 => "00001111", 34 => "11111110", 35 => "11100101", 
    36 => "00001010", 37 => "11111001", 38 => "11111110", 39 => "11100100", 
    40 => "00011001", 41 => "00001001", 42 => "11111101", 43 => "11111000", 
    44 => "11010011", 45 => "01010001", 46 => "11100110", 47 => "11101100", 
    48 => "00010011", 49 => "00010001", 50 => "11100010", 51 => "11111010", 
    52 => "00010000", 53 => "00001100", 54 => "11100110", 55 => "00001010", 
    56 => "11111111", 57 => "11100000", 58 => "00010010", 59 => "00100110", 
    60 => "00010001", 61 => "00001011", 62 => "11110011", 63 => "00011101");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

