-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity awn_forward_conv1_block_p_ZL2W1_0_1_0_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of awn_forward_conv1_block_p_ZL2W1_0_1_0_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111110", 1 => "11110100", 2 => "11010010", 3 => "00101100", 
    4 => "00000001", 5 => "00110001", 6 => "11111010", 7 => "00101000", 
    8 => "00100000", 9 => "00010111", 10 => "01010011", 11 => "00001111", 
    12 => "00110001", 13 => "00000001", 14 => "11110010", 15 => "11100101", 
    16 => "00101001", 17 => "11001010", 18 => "11100010", 19 => "10110100", 
    20 => "11010111", 21 => "11011111", 22 => "11100100", 23 => "00100010", 
    24 => "00000100", 25 => "11101100", 26 => "11011011", 27 => "00001011", 
    28 => "00010101", 29 => "01001100", 30 => "11111011", 31 => "11100011", 
    32 => "00010001", 33 => "11110110", 34 => "11110010", 35 => "11100100", 
    36 => "11111000", 37 => "01000101", 38 => "11010001", 39 => "00111101", 
    40 => "11110011", 41 => "10100100", 42 => "11111111", 43 => "00011001", 
    44 => "00110111", 45 => "00101100", 46 => "11101000", 47 => "00010100", 
    48 => "11001101", 49 => "11010001", 50 => "00001000", 51 => "11010001", 
    52 => "11010100", 53 => "11001101", 54 => "00100111", 55 => "00111001", 
    56 => "00001101", 57 => "00010111", 58 => "00000101", 59 => "00010001", 
    60 => "11001000", 61 => "11011100", 62 => "11000010", 63 => "11000110");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

