-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity awn_forward_conv2_block_p_ZL2W2_0_13_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of awn_forward_conv2_block_p_ZL2W2_0_13_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "11110010", 1 => "00010000", 2 => "00000100", 3 => "00101101", 
    4 => "00001111", 5 => "00001010", 6 => "11101110", 7 => "00010101", 
    8 => "11101110", 9 => "00001110", 10 => "00100011", 11 => "11111000", 
    12 => "11111110", 13 => "00001101", 14 => "00010100", 15 => "11111000", 
    16 => "11100010", 17 => "11111001", 18 => "00100001", 19 => "00001010", 
    20 => "11111110", 21 => "11111010", 22 => "00001001", 23 => "11111011", 
    24 => "00011000", 25 => "00001101", 26 => "00000101", 27 => "00000000", 
    28 => "00100100", 29 => "00000011", 30 => "00000010", 31 => "00011000", 
    32 => "11101000", 33 => "00110000", 34 => "11100011", 35 => "00010111", 
    36 => "11100001", 37 => "11111100", 38 => "00000000", 39 => "11111000", 
    40 => "11100111", 41 => "11110100", 42 => "00001101", 43 => "11100110", 
    44 => "00011010", 45 => "00010101", 46 => "01011011", 47 => "00001010", 
    48 => "00100111", 49 => "00000000", 50 => "11110001", 51 => "11110111", 
    52 => "11101110", 53 => "11101100", 54 => "00110010", 55 => "11111000", 
    56 => "10110110", 57 => "11001111", 58 => "00010101", 59 => "11101111", 
    60 => "00001001", 61 => "00010011", 62 => "00011011", 63 => "11101010");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

